/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Cloudmersive.APIClient.NET.DLP.Client;
using Cloudmersive.APIClient.NET.DLP.Api;
// uncomment below to import models
//using Cloudmersive.APIClient.NET.DLP.Model;

namespace Cloudmersive.APIClient.NET.DLP.Test.Api
{
    /// <summary>
    ///  Class for testing DetectApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DetectApiTests : IDisposable
    {
        private DetectApi instance;

        public DetectApiTests()
        {
            instance = new DetectApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DetectApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DetectApi
            //Assert.IsType<DetectApi>(instance);
        }

        /// <summary>
        /// Test DetectDocument
        /// </summary>
        [Fact]
        public void DetectDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpDocumentDetectionRequest body = null;
            //var response = instance.DetectDocument(body);
            //Assert.IsType<DlpDetectionResponse>(response);
        }

        /// <summary>
        /// Test DetectDocumentAdvanced
        /// </summary>
        [Fact]
        public void DetectDocumentAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpAdvancedDocumentDetectionRequest body = null;
            //var response = instance.DetectDocumentAdvanced(body);
            //Assert.IsType<DlpAdvancedDetectionResponse>(response);
        }

        /// <summary>
        /// Test DetectText
        /// </summary>
        [Fact]
        public void DetectTextTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpDetectionRequest body = null;
            //var response = instance.DetectText(body);
            //Assert.IsType<DlpDetectionResponse>(response);
        }

        /// <summary>
        /// Test DetectTextAdvanced
        /// </summary>
        [Fact]
        public void DetectTextAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpAdvancedDetectionRequest body = null;
            //var response = instance.DetectTextAdvanced(body);
            //Assert.IsType<DlpAdvancedDetectionResponse>(response);
        }
    }
}
