/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Cloudmersive.APIClient.NET.DLP.Client;
using Cloudmersive.APIClient.NET.DLP.Api;
// uncomment below to import models
//using Cloudmersive.APIClient.NET.DLP.Model;

namespace Cloudmersive.APIClient.NET.DLP.Test.Api
{
    /// <summary>
    ///  Class for testing RedactApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RedactApiTests : IDisposable
    {
        private RedactApi instance;

        public RedactApiTests()
        {
            instance = new RedactApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RedactApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RedactApi
            //Assert.IsType<RedactApi>(instance);
        }

        /// <summary>
        /// Test RedactDocument
        /// </summary>
        [Fact]
        public void RedactDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpDocumentRedactionRequest body = null;
            //var response = instance.RedactDocument(body);
            //Assert.IsType<DlpDocumentRedactionResponse>(response);
        }

        /// <summary>
        /// Test RedactDocumentAdvanced
        /// </summary>
        [Fact]
        public void RedactDocumentAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpAdvancedDocumentRedactionRequest body = null;
            //var response = instance.RedactDocumentAdvanced(body);
            //Assert.IsType<DlpAdvancedDocumentRedactionResponse>(response);
        }

        /// <summary>
        /// Test RedactText
        /// </summary>
        [Fact]
        public void RedactTextTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpRedactionRequest body = null;
            //var response = instance.RedactText(body);
            //Assert.IsType<DlpRedactionResponse>(response);
        }

        /// <summary>
        /// Test RedactTextAdvanced
        /// </summary>
        [Fact]
        public void RedactTextAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpAdvancedRedactionRequest body = null;
            //var response = instance.RedactTextAdvanced(body);
            //Assert.IsType<DlpAdvancedRedactionResponse>(response);
        }
    }
}
