/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Cloudmersive.APIClient.NET.DLP.Client;
using Cloudmersive.APIClient.NET.DLP.Api;
// uncomment below to import models
//using Cloudmersive.APIClient.NET.DLP.Model;

namespace Cloudmersive.APIClient.NET.DLP.Test.Api
{
    /// <summary>
    ///  Class for testing TasksBatchJobApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TasksBatchJobApiTests : IDisposable
    {
        private TasksBatchJobApi instance;

        public TasksBatchJobApiTests()
        {
            instance = new TasksBatchJobApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TasksBatchJobApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TasksBatchJobApi
            //Assert.IsType<TasksBatchJobApi>(instance);
        }

        /// <summary>
        /// Test DetectAudioAdvancedBatchJob
        /// </summary>
        [Fact]
        public void DetectAudioAdvancedBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpAdvancedAudioDetectionRequest body = null;
            //var response = instance.DetectAudioAdvancedBatchJob(body);
            //Assert.IsType<DlpBatchJobResult>(response);
        }

        /// <summary>
        /// Test DetectAudioBatchJob
        /// </summary>
        [Fact]
        public void DetectAudioBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpAudioDetectionRequest body = null;
            //var response = instance.DetectAudioBatchJob(body);
            //Assert.IsType<DlpBatchJobResult>(response);
        }

        /// <summary>
        /// Test GetAsyncJobStatus
        /// </summary>
        [Fact]
        public void GetAsyncJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string asyncJobID = null;
            //var response = instance.GetAsyncJobStatus(asyncJobID);
            //Assert.IsType<DlpBatchJobStatusResult>(response);
        }

        /// <summary>
        /// Test RedactAudioAdvancedBatchJob
        /// </summary>
        [Fact]
        public void RedactAudioAdvancedBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpAdvancedAudioRedactionRequest body = null;
            //var response = instance.RedactAudioAdvancedBatchJob(body);
            //Assert.IsType<DlpBatchJobResult>(response);
        }

        /// <summary>
        /// Test RedactAudioBatchJob
        /// </summary>
        [Fact]
        public void RedactAudioBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DlpAudioRedactionRequest body = null;
            //var response = instance.RedactAudioBatchJob(body);
            //Assert.IsType<DlpBatchJobResult>(response);
        }
    }
}
