. .\core.ps1

Remove-Item –path ./client –recurse

Invoke-WebRequest -Uri 'https://api.cloudmersive.com/dlp/v1/swagger.json' -OutFile '.\dlp-api-swagger.json'
(Get-Content .\dlp-api-swagger.json).replace('localhost', "api.cloudmersive.com") | Set-Content .\dlp-api-swagger.json
(Get-Content .\dlp-api-swagger.json).replace('"http"', '"https"') | Set-Content .\dlp-api-swagger.json

java -jar ./openapi-generator-cli-7.12.0.jar generate -i .\dlp-api-swagger.json -g csharp -o client -c packageconfig.json

## (Get-Content ./client/src/api/ConvertDocumentApi.js).replace('var returnType = Object;', "var returnType = 'Blob';") | Set-Content ./client/src/api/ConvertDocumentApi.js
## (Get-Content ./client/src/api/ConvertWebApi.js).replace('var returnType = Object;', "var returnType = 'Blob';") | Set-Content ./client/src/api/ConvertWebApi.js
## & npm build ./client


$csprojpath = Resolve-Path ./client/src/Cloudmersive.APIClient.NET.DLP/Cloudmersive.APIClient.NET.DLP.csproj
$csprojtestpath = Resolve-Path ./client/src/Cloudmersive.APIClient.NET.DLP.Test/Cloudmersive.APIClient.NET.DLP.Test.csproj
#$nuspecpath = Resolve-Path ./client/src/Cloudmersive.APIClient.NET.VirusScan/Cloudmersive.APIClient.NET.VirusScan.nuspec
$slnpath = Resolve-Path ./client/Cloudmersive.APIClient.NET.DLP.sln




(Get-Content $csprojpath).replace('<RepositoryUrl>https://github.com/Cloudmersive/Cloudmersive.APIClient.NET.DLP.git</RepositoryUrl>', '<RepositoryUrl>https://github.com/Cloudmersive/Cloudmersive.APIClient.NET.DLP.git</RepositoryUrl><PackageProjectUrl>https://cloudmersive.com/dlp-data-loss-prevention-api</PackageProjectUrl><PackageIconUrl>https://cloudmersive.com/images/cmsdk.png</PackageIconUrl>') | Set-Content $csprojpath




./nuget.exe restore $csprojpath -SolutionDirectory ./client

./nuget.exe restore $csprojtestpath -SolutionDirectory ./client

#C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe $slnpath /t:rebuild 
$configuration = 'Release'

dotnet build $slnpath -c $configuration

#$msbuild = Get-LatestMsBuild
#& $msbuild $slnpath /t:Rebuild /p:Configuration=$configuration



#& C:\CodeSigning\sign.ps1 ./client/src/Cloudmersive.APIClient.NET.DLP/bin/Debug/netstandard2.0/Cloudmersive.APIClient.NET.DLP.dll
#& C:\CodeSigning\sign.ps1 ./client/src/Cloudmersive.APIClient.NET.DLP/bin/Release/netstandard2.0/Cloudmersive.APIClient.NET.DLP.dll

Write-Host "Packing..."

#./nuget.exe pack $csprojpath -Properties Configuration=$configuration

dotnet pack  $csprojpath -c $configuration -o ./nupkgs

(Get-Content ./client/README.md).replace(' automatically generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project', " for the [Cloudmersive DLP API](https://cloudmersive.com/dlp-data-loss-prevention-api)") | Set-Content ./client/README.md

Copy-Item ./client/README.md ./README.md