/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.DLP.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.DLP.Model
{
    /// <summary>
    /// A single token with its timestamp from speech recognition.
    /// </summary>
    [DataContract(Name = "AudioTimestamp")]
    public partial class AudioTimestamp : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioTimestamp" /> class.
        /// </summary>
        /// <param name="token">The word or token recognized from the audio..</param>
        /// <param name="characterOffsetStart">Start position of the token in the transcript text (character offset)..</param>
        /// <param name="characterOffsetEnd">End position of the token in the transcript text (character offset)..</param>
        /// <param name="startTimeMs">Start time of the token in the audio, in milliseconds..</param>
        /// <param name="endTimeMs">End time of the token in the audio, in milliseconds..</param>
        public AudioTimestamp(string token = default(string), int characterOffsetStart = default(int), int characterOffsetEnd = default(int), long startTimeMs = default(long), long endTimeMs = default(long))
        {
            this.Token = token;
            this.CharacterOffsetStart = characterOffsetStart;
            this.CharacterOffsetEnd = characterOffsetEnd;
            this.StartTimeMs = startTimeMs;
            this.EndTimeMs = endTimeMs;
        }

        /// <summary>
        /// The word or token recognized from the audio.
        /// </summary>
        /// <value>The word or token recognized from the audio.</value>
        [DataMember(Name = "Token", EmitDefaultValue = false)]
        public string Token { get; set; }

        /// <summary>
        /// Start position of the token in the transcript text (character offset).
        /// </summary>
        /// <value>Start position of the token in the transcript text (character offset).</value>
        [DataMember(Name = "CharacterOffsetStart", EmitDefaultValue = false)]
        public int CharacterOffsetStart { get; set; }

        /// <summary>
        /// End position of the token in the transcript text (character offset).
        /// </summary>
        /// <value>End position of the token in the transcript text (character offset).</value>
        [DataMember(Name = "CharacterOffsetEnd", EmitDefaultValue = false)]
        public int CharacterOffsetEnd { get; set; }

        /// <summary>
        /// Start time of the token in the audio, in milliseconds.
        /// </summary>
        /// <value>Start time of the token in the audio, in milliseconds.</value>
        [DataMember(Name = "StartTimeMs", EmitDefaultValue = false)]
        public long StartTimeMs { get; set; }

        /// <summary>
        /// End time of the token in the audio, in milliseconds.
        /// </summary>
        /// <value>End time of the token in the audio, in milliseconds.</value>
        [DataMember(Name = "EndTimeMs", EmitDefaultValue = false)]
        public long EndTimeMs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AudioTimestamp {\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  CharacterOffsetStart: ").Append(CharacterOffsetStart).Append("\n");
            sb.Append("  CharacterOffsetEnd: ").Append(CharacterOffsetEnd).Append("\n");
            sb.Append("  StartTimeMs: ").Append(StartTimeMs).Append("\n");
            sb.Append("  EndTimeMs: ").Append(EndTimeMs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
