/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.DLP.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.DLP.Model
{
    /// <summary>
    /// Caller-defined custom PII field. The redaction LLM will look for content matching  the description and redact it as a semantic tag derived from the title  (e.g. title \&quot;internal participant code\&quot; → tag [INTERNAL-PARTICIPANT-CODE]).
    /// </summary>
    [DataContract(Name = "CustomPiiField")]
    public partial class CustomPiiField : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomPiiField" /> class.
        /// </summary>
        /// <param name="title">Short title for the custom field, also used to derive the semantic tag (uppercased, spaces/underscores replaced with hyphens)..</param>
        /// <param name="description">Description of what this field looks like, used to instruct the redaction LLM. Be specific so the LLM can locate matches..</param>
        public CustomPiiField(string title = default(string), string description = default(string))
        {
            this.Title = title;
            this.Description = description;
        }

        /// <summary>
        /// Short title for the custom field, also used to derive the semantic tag (uppercased, spaces/underscores replaced with hyphens).
        /// </summary>
        /// <value>Short title for the custom field, also used to derive the semantic tag (uppercased, spaces/underscores replaced with hyphens).</value>
        /*
        <example>internal participant code</example>
        */
        [DataMember(Name = "Title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// Description of what this field looks like, used to instruct the redaction LLM. Be specific so the LLM can locate matches.
        /// </summary>
        /// <value>Description of what this field looks like, used to instruct the redaction LLM. Be specific so the LLM can locate matches.</value>
        /*
        <example>alphanumeric study or research participant identifier code (e.g. studyMDD90231)</example>
        */
        [DataMember(Name = "Description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomPiiField {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
