/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.DLP.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.DLP.Model
{
    /// <summary>
    /// Request object for advanced DLP text detection with 29 PII detection types including health-related data.
    /// </summary>
    [DataContract(Name = "DlpAdvancedDetectionRequest")]
    public partial class DlpAdvancedDetectionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlpAdvancedDetectionRequest" /> class.
        /// </summary>
        /// <param name="inputText">Text to scan for PII and sensitive data..</param>
        /// <param name="allowEmailAddress">Set to true to allow email addresses in the input text and not flag them as PII..</param>
        /// <param name="allowPhoneNumber">Set to true to allow phone numbers in the input text and not flag them as PII..</param>
        /// <param name="allowStreetAddress">Set to true to allow street addresses in the input text and not flag them as PII..</param>
        /// <param name="allowPersonName">Set to true to allow person names in the input text and not flag them as PII..</param>
        /// <param name="allowBirthDate">Set to true to allow birth dates in the input text and not flag them as PII..</param>
        /// <param name="allowPassportNumber">Set to true to allow passport numbers in the input text and not flag them as PII..</param>
        /// <param name="allowDriversLicense">Set to true to allow drivers license numbers in the input text and not flag them as PII..</param>
        /// <param name="allowSocialSecurityNumber">Set to true to allow social security numbers in the input text and not flag them as PII..</param>
        /// <param name="allowTaxpayerID">Set to true to allow taxpayer IDs in the input text and not flag them as PII..</param>
        /// <param name="allowCreditCardNumber">Set to true to allow credit card numbers in the input text and not flag them as PII..</param>
        /// <param name="allowCreditCardExpirationDate">Set to true to allow credit card expiration dates in the input text and not flag them as PII..</param>
        /// <param name="allowCreditCardVerificationCode">Set to true to allow credit card verification codes in the input text and not flag them as PII..</param>
        /// <param name="allowBankAccountNumber">Set to true to allow bank account numbers in the input text and not flag them as PII..</param>
        /// <param name="allowIBAN">Set to true to allow IBANs in the input text and not flag them as PII..</param>
        /// <param name="allowHealthInsuranceNumber">Set to true to allow health insurance numbers in the input text and not flag them as PII..</param>
        /// <param name="allowBearerToken">Set to true to allow bearer tokens in the input text and not flag them as PII..</param>
        /// <param name="allowHttpCookie">Set to true to allow HTTP cookies in the input text and not flag them as PII..</param>
        /// <param name="allowPrivateKeys">Set to true to allow private keys in the input text and not flag them as PII..</param>
        /// <param name="allowCredentials">Set to true to allow credentials (usernames/passwords) in the input text and not flag them as PII..</param>
        /// <param name="allowDeepWebUrls">Set to true to allow deep web URLs (.onion) in the input text and not flag them as PII..</param>
        /// <param name="allowSourceCode">Set to true to allow source code in the input text and not flag it as sensitive data..</param>
        /// <param name="allowIpAddress">Set to true to allow IP addresses in the input text and not flag them as PII..</param>
        /// <param name="allowMacAddress">Set to true to allow MAC addresses in the input text and not flag them as PII..</param>
        /// <param name="allowHealthInsuranceMemberID">Set to true to allow health insurance member IDs in the input text and not flag them as PHI..</param>
        /// <param name="allowHealthInjuryOrDisease">Set to true to allow references to injuries or diseases in the input text and not flag them as PHI..</param>
        /// <param name="allowHealthTypeOfTreatment">Set to true to allow references to types of medical treatment in the input text and not flag them as PHI..</param>
        /// <param name="allowHealthDateAndTimeOfTreatment">Set to true to allow dates and times of medical treatment in the input text and not flag them as PHI..</param>
        /// <param name="allowHealthPlanBeneficiaryNumber">Set to true to allow health plan beneficiary numbers in the input text and not flag them as PHI..</param>
        /// <param name="allowHealthPaymentsMadeForTreatment">Set to true to allow payments made for medical treatment in the input text and not flag them as PHI..</param>
        /// <param name="allowVehicleID">Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the input text and not flag them as PII..</param>
        /// <param name="allowDeviceID">Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the input text and not flag them as PII..</param>
        /// <param name="allowNamesOfRelatives">Set to true to allow names of relatives in the input text and not flag them as PII..</param>
        /// <param name="allowHealthUniversalRecordLocator">Set to true to allow health universal record locators (URLs) in the input text and not flag them as PHI..</param>
        /// <param name="allowBiometrics">Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the input text and not flag them as PII..</param>
        /// <param name="provideAnalysisRationale">Set to true to include a natural language rationale explaining why each detection conclusion was formed..</param>
        public DlpAdvancedDetectionRequest(string inputText = default(string), bool allowEmailAddress = default(bool), bool allowPhoneNumber = default(bool), bool allowStreetAddress = default(bool), bool allowPersonName = default(bool), bool allowBirthDate = default(bool), bool allowPassportNumber = default(bool), bool allowDriversLicense = default(bool), bool allowSocialSecurityNumber = default(bool), bool allowTaxpayerID = default(bool), bool allowCreditCardNumber = default(bool), bool allowCreditCardExpirationDate = default(bool), bool allowCreditCardVerificationCode = default(bool), bool allowBankAccountNumber = default(bool), bool allowIBAN = default(bool), bool allowHealthInsuranceNumber = default(bool), bool allowBearerToken = default(bool), bool allowHttpCookie = default(bool), bool allowPrivateKeys = default(bool), bool allowCredentials = default(bool), bool allowDeepWebUrls = default(bool), bool allowSourceCode = default(bool), bool allowIpAddress = default(bool), bool allowMacAddress = default(bool), bool allowHealthInsuranceMemberID = default(bool), bool allowHealthInjuryOrDisease = default(bool), bool allowHealthTypeOfTreatment = default(bool), bool allowHealthDateAndTimeOfTreatment = default(bool), bool allowHealthPlanBeneficiaryNumber = default(bool), bool allowHealthPaymentsMadeForTreatment = default(bool), bool allowVehicleID = default(bool), bool allowDeviceID = default(bool), bool allowNamesOfRelatives = default(bool), bool allowHealthUniversalRecordLocator = default(bool), bool allowBiometrics = default(bool), bool provideAnalysisRationale = default(bool))
        {
            this.InputText = inputText;
            this.AllowEmailAddress = allowEmailAddress;
            this.AllowPhoneNumber = allowPhoneNumber;
            this.AllowStreetAddress = allowStreetAddress;
            this.AllowPersonName = allowPersonName;
            this.AllowBirthDate = allowBirthDate;
            this.AllowPassportNumber = allowPassportNumber;
            this.AllowDriversLicense = allowDriversLicense;
            this.AllowSocialSecurityNumber = allowSocialSecurityNumber;
            this.AllowTaxpayerID = allowTaxpayerID;
            this.AllowCreditCardNumber = allowCreditCardNumber;
            this.AllowCreditCardExpirationDate = allowCreditCardExpirationDate;
            this.AllowCreditCardVerificationCode = allowCreditCardVerificationCode;
            this.AllowBankAccountNumber = allowBankAccountNumber;
            this.AllowIBAN = allowIBAN;
            this.AllowHealthInsuranceNumber = allowHealthInsuranceNumber;
            this.AllowBearerToken = allowBearerToken;
            this.AllowHttpCookie = allowHttpCookie;
            this.AllowPrivateKeys = allowPrivateKeys;
            this.AllowCredentials = allowCredentials;
            this.AllowDeepWebUrls = allowDeepWebUrls;
            this.AllowSourceCode = allowSourceCode;
            this.AllowIpAddress = allowIpAddress;
            this.AllowMacAddress = allowMacAddress;
            this.AllowHealthInsuranceMemberID = allowHealthInsuranceMemberID;
            this.AllowHealthInjuryOrDisease = allowHealthInjuryOrDisease;
            this.AllowHealthTypeOfTreatment = allowHealthTypeOfTreatment;
            this.AllowHealthDateAndTimeOfTreatment = allowHealthDateAndTimeOfTreatment;
            this.AllowHealthPlanBeneficiaryNumber = allowHealthPlanBeneficiaryNumber;
            this.AllowHealthPaymentsMadeForTreatment = allowHealthPaymentsMadeForTreatment;
            this.AllowVehicleID = allowVehicleID;
            this.AllowDeviceID = allowDeviceID;
            this.AllowNamesOfRelatives = allowNamesOfRelatives;
            this.AllowHealthUniversalRecordLocator = allowHealthUniversalRecordLocator;
            this.AllowBiometrics = allowBiometrics;
            this.ProvideAnalysisRationale = provideAnalysisRationale;
        }

        /// <summary>
        /// Text to scan for PII and sensitive data.
        /// </summary>
        /// <value>Text to scan for PII and sensitive data.</value>
        /*
        <example>Hello, world!</example>
        */
        [DataMember(Name = "InputText", EmitDefaultValue = false)]
        public string InputText { get; set; }

        /// <summary>
        /// Set to true to allow email addresses in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow email addresses in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowEmailAddress", EmitDefaultValue = true)]
        public bool AllowEmailAddress { get; set; }

        /// <summary>
        /// Set to true to allow phone numbers in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow phone numbers in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPhoneNumber", EmitDefaultValue = true)]
        public bool AllowPhoneNumber { get; set; }

        /// <summary>
        /// Set to true to allow street addresses in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow street addresses in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowStreetAddress", EmitDefaultValue = true)]
        public bool AllowStreetAddress { get; set; }

        /// <summary>
        /// Set to true to allow person names in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow person names in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPersonName", EmitDefaultValue = true)]
        public bool AllowPersonName { get; set; }

        /// <summary>
        /// Set to true to allow birth dates in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow birth dates in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowBirthDate", EmitDefaultValue = true)]
        public bool AllowBirthDate { get; set; }

        /// <summary>
        /// Set to true to allow passport numbers in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow passport numbers in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPassportNumber", EmitDefaultValue = true)]
        public bool AllowPassportNumber { get; set; }

        /// <summary>
        /// Set to true to allow drivers license numbers in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow drivers license numbers in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowDriversLicense", EmitDefaultValue = true)]
        public bool AllowDriversLicense { get; set; }

        /// <summary>
        /// Set to true to allow social security numbers in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow social security numbers in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowSocialSecurityNumber", EmitDefaultValue = true)]
        public bool AllowSocialSecurityNumber { get; set; }

        /// <summary>
        /// Set to true to allow taxpayer IDs in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow taxpayer IDs in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowTaxpayerID", EmitDefaultValue = true)]
        public bool AllowTaxpayerID { get; set; }

        /// <summary>
        /// Set to true to allow credit card numbers in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credit card numbers in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowCreditCardNumber", EmitDefaultValue = true)]
        public bool AllowCreditCardNumber { get; set; }

        /// <summary>
        /// Set to true to allow credit card expiration dates in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credit card expiration dates in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowCreditCardExpirationDate", EmitDefaultValue = true)]
        public bool AllowCreditCardExpirationDate { get; set; }

        /// <summary>
        /// Set to true to allow credit card verification codes in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credit card verification codes in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowCreditCardVerificationCode", EmitDefaultValue = true)]
        public bool AllowCreditCardVerificationCode { get; set; }

        /// <summary>
        /// Set to true to allow bank account numbers in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow bank account numbers in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowBankAccountNumber", EmitDefaultValue = true)]
        public bool AllowBankAccountNumber { get; set; }

        /// <summary>
        /// Set to true to allow IBANs in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow IBANs in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowIBAN", EmitDefaultValue = true)]
        public bool AllowIBAN { get; set; }

        /// <summary>
        /// Set to true to allow health insurance numbers in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow health insurance numbers in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthInsuranceNumber", EmitDefaultValue = true)]
        public bool AllowHealthInsuranceNumber { get; set; }

        /// <summary>
        /// Set to true to allow bearer tokens in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow bearer tokens in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowBearerToken", EmitDefaultValue = true)]
        public bool AllowBearerToken { get; set; }

        /// <summary>
        /// Set to true to allow HTTP cookies in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow HTTP cookies in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHttpCookie", EmitDefaultValue = true)]
        public bool AllowHttpCookie { get; set; }

        /// <summary>
        /// Set to true to allow private keys in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow private keys in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPrivateKeys", EmitDefaultValue = true)]
        public bool AllowPrivateKeys { get; set; }

        /// <summary>
        /// Set to true to allow credentials (usernames/passwords) in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credentials (usernames/passwords) in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowCredentials", EmitDefaultValue = true)]
        public bool AllowCredentials { get; set; }

        /// <summary>
        /// Set to true to allow deep web URLs (.onion) in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow deep web URLs (.onion) in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowDeepWebUrls", EmitDefaultValue = true)]
        public bool AllowDeepWebUrls { get; set; }

        /// <summary>
        /// Set to true to allow source code in the input text and not flag it as sensitive data.
        /// </summary>
        /// <value>Set to true to allow source code in the input text and not flag it as sensitive data.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowSourceCode", EmitDefaultValue = true)]
        public bool AllowSourceCode { get; set; }

        /// <summary>
        /// Set to true to allow IP addresses in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow IP addresses in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowIpAddress", EmitDefaultValue = true)]
        public bool AllowIpAddress { get; set; }

        /// <summary>
        /// Set to true to allow MAC addresses in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow MAC addresses in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowMacAddress", EmitDefaultValue = true)]
        public bool AllowMacAddress { get; set; }

        /// <summary>
        /// Set to true to allow health insurance member IDs in the input text and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow health insurance member IDs in the input text and not flag them as PHI.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthInsuranceMemberID", EmitDefaultValue = true)]
        public bool AllowHealthInsuranceMemberID { get; set; }

        /// <summary>
        /// Set to true to allow references to injuries or diseases in the input text and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow references to injuries or diseases in the input text and not flag them as PHI.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthInjuryOrDisease", EmitDefaultValue = true)]
        public bool AllowHealthInjuryOrDisease { get; set; }

        /// <summary>
        /// Set to true to allow references to types of medical treatment in the input text and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow references to types of medical treatment in the input text and not flag them as PHI.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthTypeOfTreatment", EmitDefaultValue = true)]
        public bool AllowHealthTypeOfTreatment { get; set; }

        /// <summary>
        /// Set to true to allow dates and times of medical treatment in the input text and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow dates and times of medical treatment in the input text and not flag them as PHI.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthDateAndTimeOfTreatment", EmitDefaultValue = true)]
        public bool AllowHealthDateAndTimeOfTreatment { get; set; }

        /// <summary>
        /// Set to true to allow health plan beneficiary numbers in the input text and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow health plan beneficiary numbers in the input text and not flag them as PHI.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthPlanBeneficiaryNumber", EmitDefaultValue = true)]
        public bool AllowHealthPlanBeneficiaryNumber { get; set; }

        /// <summary>
        /// Set to true to allow payments made for medical treatment in the input text and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow payments made for medical treatment in the input text and not flag them as PHI.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthPaymentsMadeForTreatment", EmitDefaultValue = true)]
        public bool AllowHealthPaymentsMadeForTreatment { get; set; }

        /// <summary>
        /// Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowVehicleID", EmitDefaultValue = true)]
        public bool AllowVehicleID { get; set; }

        /// <summary>
        /// Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowDeviceID", EmitDefaultValue = true)]
        public bool AllowDeviceID { get; set; }

        /// <summary>
        /// Set to true to allow names of relatives in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow names of relatives in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowNamesOfRelatives", EmitDefaultValue = true)]
        public bool AllowNamesOfRelatives { get; set; }

        /// <summary>
        /// Set to true to allow health universal record locators (URLs) in the input text and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow health universal record locators (URLs) in the input text and not flag them as PHI.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthUniversalRecordLocator", EmitDefaultValue = true)]
        public bool AllowHealthUniversalRecordLocator { get; set; }

        /// <summary>
        /// Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the input text and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the input text and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowBiometrics", EmitDefaultValue = true)]
        public bool AllowBiometrics { get; set; }

        /// <summary>
        /// Set to true to include a natural language rationale explaining why each detection conclusion was formed.
        /// </summary>
        /// <value>Set to true to include a natural language rationale explaining why each detection conclusion was formed.</value>
        [DataMember(Name = "ProvideAnalysisRationale", EmitDefaultValue = true)]
        public bool ProvideAnalysisRationale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DlpAdvancedDetectionRequest {\n");
            sb.Append("  InputText: ").Append(InputText).Append("\n");
            sb.Append("  AllowEmailAddress: ").Append(AllowEmailAddress).Append("\n");
            sb.Append("  AllowPhoneNumber: ").Append(AllowPhoneNumber).Append("\n");
            sb.Append("  AllowStreetAddress: ").Append(AllowStreetAddress).Append("\n");
            sb.Append("  AllowPersonName: ").Append(AllowPersonName).Append("\n");
            sb.Append("  AllowBirthDate: ").Append(AllowBirthDate).Append("\n");
            sb.Append("  AllowPassportNumber: ").Append(AllowPassportNumber).Append("\n");
            sb.Append("  AllowDriversLicense: ").Append(AllowDriversLicense).Append("\n");
            sb.Append("  AllowSocialSecurityNumber: ").Append(AllowSocialSecurityNumber).Append("\n");
            sb.Append("  AllowTaxpayerID: ").Append(AllowTaxpayerID).Append("\n");
            sb.Append("  AllowCreditCardNumber: ").Append(AllowCreditCardNumber).Append("\n");
            sb.Append("  AllowCreditCardExpirationDate: ").Append(AllowCreditCardExpirationDate).Append("\n");
            sb.Append("  AllowCreditCardVerificationCode: ").Append(AllowCreditCardVerificationCode).Append("\n");
            sb.Append("  AllowBankAccountNumber: ").Append(AllowBankAccountNumber).Append("\n");
            sb.Append("  AllowIBAN: ").Append(AllowIBAN).Append("\n");
            sb.Append("  AllowHealthInsuranceNumber: ").Append(AllowHealthInsuranceNumber).Append("\n");
            sb.Append("  AllowBearerToken: ").Append(AllowBearerToken).Append("\n");
            sb.Append("  AllowHttpCookie: ").Append(AllowHttpCookie).Append("\n");
            sb.Append("  AllowPrivateKeys: ").Append(AllowPrivateKeys).Append("\n");
            sb.Append("  AllowCredentials: ").Append(AllowCredentials).Append("\n");
            sb.Append("  AllowDeepWebUrls: ").Append(AllowDeepWebUrls).Append("\n");
            sb.Append("  AllowSourceCode: ").Append(AllowSourceCode).Append("\n");
            sb.Append("  AllowIpAddress: ").Append(AllowIpAddress).Append("\n");
            sb.Append("  AllowMacAddress: ").Append(AllowMacAddress).Append("\n");
            sb.Append("  AllowHealthInsuranceMemberID: ").Append(AllowHealthInsuranceMemberID).Append("\n");
            sb.Append("  AllowHealthInjuryOrDisease: ").Append(AllowHealthInjuryOrDisease).Append("\n");
            sb.Append("  AllowHealthTypeOfTreatment: ").Append(AllowHealthTypeOfTreatment).Append("\n");
            sb.Append("  AllowHealthDateAndTimeOfTreatment: ").Append(AllowHealthDateAndTimeOfTreatment).Append("\n");
            sb.Append("  AllowHealthPlanBeneficiaryNumber: ").Append(AllowHealthPlanBeneficiaryNumber).Append("\n");
            sb.Append("  AllowHealthPaymentsMadeForTreatment: ").Append(AllowHealthPaymentsMadeForTreatment).Append("\n");
            sb.Append("  AllowVehicleID: ").Append(AllowVehicleID).Append("\n");
            sb.Append("  AllowDeviceID: ").Append(AllowDeviceID).Append("\n");
            sb.Append("  AllowNamesOfRelatives: ").Append(AllowNamesOfRelatives).Append("\n");
            sb.Append("  AllowHealthUniversalRecordLocator: ").Append(AllowHealthUniversalRecordLocator).Append("\n");
            sb.Append("  AllowBiometrics: ").Append(AllowBiometrics).Append("\n");
            sb.Append("  ProvideAnalysisRationale: ").Append(ProvideAnalysisRationale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
