/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.DLP.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.DLP.Model
{
    /// <summary>
    /// Response object for advanced DLP text detection with 29 PII detection types including health-related data.
    /// </summary>
    [DataContract(Name = "DlpAdvancedDetectionResponse")]
    public partial class DlpAdvancedDetectionResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlpAdvancedDetectionResponse" /> class.
        /// </summary>
        /// <param name="cleanResult">True if no disallowed PII or sensitive data types were detected in the input text; false if any disallowed type was found..</param>
        /// <param name="containsEmailAddress">True if the input text contains email addresses..</param>
        /// <param name="containsPhoneNumber">True if the input text contains phone numbers..</param>
        /// <param name="containsStreetAddress">True if the input text contains street addresses..</param>
        /// <param name="containsPersonName">True if the input text contains person names..</param>
        /// <param name="containsBirthDate">True if the input text contains birth dates..</param>
        /// <param name="containsPassportNumber">True if the input text contains passport numbers..</param>
        /// <param name="containsDriversLicense">True if the input text contains drivers license numbers..</param>
        /// <param name="containsSocialSecurityNumber">True if the input text contains social security numbers..</param>
        /// <param name="containsTaxpayerID">True if the input text contains taxpayer IDs..</param>
        /// <param name="containsCreditCardNumber">True if the input text contains credit card numbers..</param>
        /// <param name="containsCreditCardExpirationDate">True if the input text contains credit card expiration dates..</param>
        /// <param name="containsCreditCardVerificationCode">True if the input text contains credit card verification codes..</param>
        /// <param name="containsBankAccountNumber">True if the input text contains bank account numbers..</param>
        /// <param name="containsIBAN">True if the input text contains IBANs..</param>
        /// <param name="containsHealthInsuranceNumber">True if the input text contains health insurance numbers..</param>
        /// <param name="containsBearerToken">True if the input text contains bearer tokens..</param>
        /// <param name="containsHttpCookie">True if the input text contains HTTP cookies..</param>
        /// <param name="containsPrivateKeys">True if the input text contains private keys..</param>
        /// <param name="containsCredentials">True if the input text contains credentials (usernames/passwords)..</param>
        /// <param name="containsDeepWebUrls">True if the input text contains deep web URLs (.onion)..</param>
        /// <param name="containsSourceCode">True if the input text contains source code..</param>
        /// <param name="containsIpAddress">True if the input text contains IP addresses..</param>
        /// <param name="containsMacAddress">True if the input text contains MAC addresses..</param>
        /// <param name="containsHealthInsuranceMemberID">True if the input text contains health insurance member IDs..</param>
        /// <param name="containsHealthInjuryOrDisease">True if the input text contains references to injuries or diseases..</param>
        /// <param name="containsHealthTypeOfTreatment">True if the input text contains references to types of medical treatment..</param>
        /// <param name="containsHealthDateAndTimeOfTreatment">True if the input text contains dates and times of medical treatment..</param>
        /// <param name="containsHealthPlanBeneficiaryNumber">True if the input text contains health plan beneficiary numbers..</param>
        /// <param name="containsHealthPaymentsMadeForTreatment">True if the input text contains payments made for medical treatment..</param>
        /// <param name="containsFaces">True if the document contains identifiable human faces..</param>
        /// <param name="containsVehicleID">True if the input contains vehicle identifiers (e.g. license plates, VINs)..</param>
        /// <param name="containsDeviceID">True if the input contains device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs)..</param>
        /// <param name="containsNamesOfRelatives">True if the input contains names of relatives..</param>
        /// <param name="containsHealthUniversalRecordLocator">True if the input contains health universal record locators (URLs)..</param>
        /// <param name="containsBiometrics">True if the input contains biometric data references (e.g. fingerprints, retinal scans, voiceprints)..</param>
        /// <param name="analysisRationale">Rationale for why the conclusion was formed. Only populated when ProvideAnalysisRationale is set to true in the request..</param>
        public DlpAdvancedDetectionResponse(bool cleanResult = default(bool), bool containsEmailAddress = default(bool), bool containsPhoneNumber = default(bool), bool containsStreetAddress = default(bool), bool containsPersonName = default(bool), bool containsBirthDate = default(bool), bool containsPassportNumber = default(bool), bool containsDriversLicense = default(bool), bool containsSocialSecurityNumber = default(bool), bool containsTaxpayerID = default(bool), bool containsCreditCardNumber = default(bool), bool containsCreditCardExpirationDate = default(bool), bool containsCreditCardVerificationCode = default(bool), bool containsBankAccountNumber = default(bool), bool containsIBAN = default(bool), bool containsHealthInsuranceNumber = default(bool), bool containsBearerToken = default(bool), bool containsHttpCookie = default(bool), bool containsPrivateKeys = default(bool), bool containsCredentials = default(bool), bool containsDeepWebUrls = default(bool), bool containsSourceCode = default(bool), bool containsIpAddress = default(bool), bool containsMacAddress = default(bool), bool containsHealthInsuranceMemberID = default(bool), bool containsHealthInjuryOrDisease = default(bool), bool containsHealthTypeOfTreatment = default(bool), bool containsHealthDateAndTimeOfTreatment = default(bool), bool containsHealthPlanBeneficiaryNumber = default(bool), bool containsHealthPaymentsMadeForTreatment = default(bool), bool containsFaces = default(bool), bool containsVehicleID = default(bool), bool containsDeviceID = default(bool), bool containsNamesOfRelatives = default(bool), bool containsHealthUniversalRecordLocator = default(bool), bool containsBiometrics = default(bool), string analysisRationale = default(string))
        {
            this.CleanResult = cleanResult;
            this.ContainsEmailAddress = containsEmailAddress;
            this.ContainsPhoneNumber = containsPhoneNumber;
            this.ContainsStreetAddress = containsStreetAddress;
            this.ContainsPersonName = containsPersonName;
            this.ContainsBirthDate = containsBirthDate;
            this.ContainsPassportNumber = containsPassportNumber;
            this.ContainsDriversLicense = containsDriversLicense;
            this.ContainsSocialSecurityNumber = containsSocialSecurityNumber;
            this.ContainsTaxpayerID = containsTaxpayerID;
            this.ContainsCreditCardNumber = containsCreditCardNumber;
            this.ContainsCreditCardExpirationDate = containsCreditCardExpirationDate;
            this.ContainsCreditCardVerificationCode = containsCreditCardVerificationCode;
            this.ContainsBankAccountNumber = containsBankAccountNumber;
            this.ContainsIBAN = containsIBAN;
            this.ContainsHealthInsuranceNumber = containsHealthInsuranceNumber;
            this.ContainsBearerToken = containsBearerToken;
            this.ContainsHttpCookie = containsHttpCookie;
            this.ContainsPrivateKeys = containsPrivateKeys;
            this.ContainsCredentials = containsCredentials;
            this.ContainsDeepWebUrls = containsDeepWebUrls;
            this.ContainsSourceCode = containsSourceCode;
            this.ContainsIpAddress = containsIpAddress;
            this.ContainsMacAddress = containsMacAddress;
            this.ContainsHealthInsuranceMemberID = containsHealthInsuranceMemberID;
            this.ContainsHealthInjuryOrDisease = containsHealthInjuryOrDisease;
            this.ContainsHealthTypeOfTreatment = containsHealthTypeOfTreatment;
            this.ContainsHealthDateAndTimeOfTreatment = containsHealthDateAndTimeOfTreatment;
            this.ContainsHealthPlanBeneficiaryNumber = containsHealthPlanBeneficiaryNumber;
            this.ContainsHealthPaymentsMadeForTreatment = containsHealthPaymentsMadeForTreatment;
            this.ContainsFaces = containsFaces;
            this.ContainsVehicleID = containsVehicleID;
            this.ContainsDeviceID = containsDeviceID;
            this.ContainsNamesOfRelatives = containsNamesOfRelatives;
            this.ContainsHealthUniversalRecordLocator = containsHealthUniversalRecordLocator;
            this.ContainsBiometrics = containsBiometrics;
            this.AnalysisRationale = analysisRationale;
        }

        /// <summary>
        /// True if no disallowed PII or sensitive data types were detected in the input text; false if any disallowed type was found.
        /// </summary>
        /// <value>True if no disallowed PII or sensitive data types were detected in the input text; false if any disallowed type was found.</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// True if the input text contains email addresses.
        /// </summary>
        /// <value>True if the input text contains email addresses.</value>
        [DataMember(Name = "ContainsEmailAddress", EmitDefaultValue = true)]
        public bool ContainsEmailAddress { get; set; }

        /// <summary>
        /// True if the input text contains phone numbers.
        /// </summary>
        /// <value>True if the input text contains phone numbers.</value>
        [DataMember(Name = "ContainsPhoneNumber", EmitDefaultValue = true)]
        public bool ContainsPhoneNumber { get; set; }

        /// <summary>
        /// True if the input text contains street addresses.
        /// </summary>
        /// <value>True if the input text contains street addresses.</value>
        [DataMember(Name = "ContainsStreetAddress", EmitDefaultValue = true)]
        public bool ContainsStreetAddress { get; set; }

        /// <summary>
        /// True if the input text contains person names.
        /// </summary>
        /// <value>True if the input text contains person names.</value>
        [DataMember(Name = "ContainsPersonName", EmitDefaultValue = true)]
        public bool ContainsPersonName { get; set; }

        /// <summary>
        /// True if the input text contains birth dates.
        /// </summary>
        /// <value>True if the input text contains birth dates.</value>
        [DataMember(Name = "ContainsBirthDate", EmitDefaultValue = true)]
        public bool ContainsBirthDate { get; set; }

        /// <summary>
        /// True if the input text contains passport numbers.
        /// </summary>
        /// <value>True if the input text contains passport numbers.</value>
        [DataMember(Name = "ContainsPassportNumber", EmitDefaultValue = true)]
        public bool ContainsPassportNumber { get; set; }

        /// <summary>
        /// True if the input text contains drivers license numbers.
        /// </summary>
        /// <value>True if the input text contains drivers license numbers.</value>
        [DataMember(Name = "ContainsDriversLicense", EmitDefaultValue = true)]
        public bool ContainsDriversLicense { get; set; }

        /// <summary>
        /// True if the input text contains social security numbers.
        /// </summary>
        /// <value>True if the input text contains social security numbers.</value>
        [DataMember(Name = "ContainsSocialSecurityNumber", EmitDefaultValue = true)]
        public bool ContainsSocialSecurityNumber { get; set; }

        /// <summary>
        /// True if the input text contains taxpayer IDs.
        /// </summary>
        /// <value>True if the input text contains taxpayer IDs.</value>
        [DataMember(Name = "ContainsTaxpayerID", EmitDefaultValue = true)]
        public bool ContainsTaxpayerID { get; set; }

        /// <summary>
        /// True if the input text contains credit card numbers.
        /// </summary>
        /// <value>True if the input text contains credit card numbers.</value>
        [DataMember(Name = "ContainsCreditCardNumber", EmitDefaultValue = true)]
        public bool ContainsCreditCardNumber { get; set; }

        /// <summary>
        /// True if the input text contains credit card expiration dates.
        /// </summary>
        /// <value>True if the input text contains credit card expiration dates.</value>
        [DataMember(Name = "ContainsCreditCardExpirationDate", EmitDefaultValue = true)]
        public bool ContainsCreditCardExpirationDate { get; set; }

        /// <summary>
        /// True if the input text contains credit card verification codes.
        /// </summary>
        /// <value>True if the input text contains credit card verification codes.</value>
        [DataMember(Name = "ContainsCreditCardVerificationCode", EmitDefaultValue = true)]
        public bool ContainsCreditCardVerificationCode { get; set; }

        /// <summary>
        /// True if the input text contains bank account numbers.
        /// </summary>
        /// <value>True if the input text contains bank account numbers.</value>
        [DataMember(Name = "ContainsBankAccountNumber", EmitDefaultValue = true)]
        public bool ContainsBankAccountNumber { get; set; }

        /// <summary>
        /// True if the input text contains IBANs.
        /// </summary>
        /// <value>True if the input text contains IBANs.</value>
        [DataMember(Name = "ContainsIBAN", EmitDefaultValue = true)]
        public bool ContainsIBAN { get; set; }

        /// <summary>
        /// True if the input text contains health insurance numbers.
        /// </summary>
        /// <value>True if the input text contains health insurance numbers.</value>
        [DataMember(Name = "ContainsHealthInsuranceNumber", EmitDefaultValue = true)]
        public bool ContainsHealthInsuranceNumber { get; set; }

        /// <summary>
        /// True if the input text contains bearer tokens.
        /// </summary>
        /// <value>True if the input text contains bearer tokens.</value>
        [DataMember(Name = "ContainsBearerToken", EmitDefaultValue = true)]
        public bool ContainsBearerToken { get; set; }

        /// <summary>
        /// True if the input text contains HTTP cookies.
        /// </summary>
        /// <value>True if the input text contains HTTP cookies.</value>
        [DataMember(Name = "ContainsHttpCookie", EmitDefaultValue = true)]
        public bool ContainsHttpCookie { get; set; }

        /// <summary>
        /// True if the input text contains private keys.
        /// </summary>
        /// <value>True if the input text contains private keys.</value>
        [DataMember(Name = "ContainsPrivateKeys", EmitDefaultValue = true)]
        public bool ContainsPrivateKeys { get; set; }

        /// <summary>
        /// True if the input text contains credentials (usernames/passwords).
        /// </summary>
        /// <value>True if the input text contains credentials (usernames/passwords).</value>
        [DataMember(Name = "ContainsCredentials", EmitDefaultValue = true)]
        public bool ContainsCredentials { get; set; }

        /// <summary>
        /// True if the input text contains deep web URLs (.onion).
        /// </summary>
        /// <value>True if the input text contains deep web URLs (.onion).</value>
        [DataMember(Name = "ContainsDeepWebUrls", EmitDefaultValue = true)]
        public bool ContainsDeepWebUrls { get; set; }

        /// <summary>
        /// True if the input text contains source code.
        /// </summary>
        /// <value>True if the input text contains source code.</value>
        [DataMember(Name = "ContainsSourceCode", EmitDefaultValue = true)]
        public bool ContainsSourceCode { get; set; }

        /// <summary>
        /// True if the input text contains IP addresses.
        /// </summary>
        /// <value>True if the input text contains IP addresses.</value>
        [DataMember(Name = "ContainsIpAddress", EmitDefaultValue = true)]
        public bool ContainsIpAddress { get; set; }

        /// <summary>
        /// True if the input text contains MAC addresses.
        /// </summary>
        /// <value>True if the input text contains MAC addresses.</value>
        [DataMember(Name = "ContainsMacAddress", EmitDefaultValue = true)]
        public bool ContainsMacAddress { get; set; }

        /// <summary>
        /// True if the input text contains health insurance member IDs.
        /// </summary>
        /// <value>True if the input text contains health insurance member IDs.</value>
        [DataMember(Name = "ContainsHealthInsuranceMemberID", EmitDefaultValue = true)]
        public bool ContainsHealthInsuranceMemberID { get; set; }

        /// <summary>
        /// True if the input text contains references to injuries or diseases.
        /// </summary>
        /// <value>True if the input text contains references to injuries or diseases.</value>
        [DataMember(Name = "ContainsHealthInjuryOrDisease", EmitDefaultValue = true)]
        public bool ContainsHealthInjuryOrDisease { get; set; }

        /// <summary>
        /// True if the input text contains references to types of medical treatment.
        /// </summary>
        /// <value>True if the input text contains references to types of medical treatment.</value>
        [DataMember(Name = "ContainsHealthTypeOfTreatment", EmitDefaultValue = true)]
        public bool ContainsHealthTypeOfTreatment { get; set; }

        /// <summary>
        /// True if the input text contains dates and times of medical treatment.
        /// </summary>
        /// <value>True if the input text contains dates and times of medical treatment.</value>
        [DataMember(Name = "ContainsHealthDateAndTimeOfTreatment", EmitDefaultValue = true)]
        public bool ContainsHealthDateAndTimeOfTreatment { get; set; }

        /// <summary>
        /// True if the input text contains health plan beneficiary numbers.
        /// </summary>
        /// <value>True if the input text contains health plan beneficiary numbers.</value>
        [DataMember(Name = "ContainsHealthPlanBeneficiaryNumber", EmitDefaultValue = true)]
        public bool ContainsHealthPlanBeneficiaryNumber { get; set; }

        /// <summary>
        /// True if the input text contains payments made for medical treatment.
        /// </summary>
        /// <value>True if the input text contains payments made for medical treatment.</value>
        [DataMember(Name = "ContainsHealthPaymentsMadeForTreatment", EmitDefaultValue = true)]
        public bool ContainsHealthPaymentsMadeForTreatment { get; set; }

        /// <summary>
        /// True if the document contains identifiable human faces.
        /// </summary>
        /// <value>True if the document contains identifiable human faces.</value>
        [DataMember(Name = "ContainsFaces", EmitDefaultValue = true)]
        public bool ContainsFaces { get; set; }

        /// <summary>
        /// True if the input contains vehicle identifiers (e.g. license plates, VINs).
        /// </summary>
        /// <value>True if the input contains vehicle identifiers (e.g. license plates, VINs).</value>
        [DataMember(Name = "ContainsVehicleID", EmitDefaultValue = true)]
        public bool ContainsVehicleID { get; set; }

        /// <summary>
        /// True if the input contains device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs).
        /// </summary>
        /// <value>True if the input contains device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs).</value>
        [DataMember(Name = "ContainsDeviceID", EmitDefaultValue = true)]
        public bool ContainsDeviceID { get; set; }

        /// <summary>
        /// True if the input contains names of relatives.
        /// </summary>
        /// <value>True if the input contains names of relatives.</value>
        [DataMember(Name = "ContainsNamesOfRelatives", EmitDefaultValue = true)]
        public bool ContainsNamesOfRelatives { get; set; }

        /// <summary>
        /// True if the input contains health universal record locators (URLs).
        /// </summary>
        /// <value>True if the input contains health universal record locators (URLs).</value>
        [DataMember(Name = "ContainsHealthUniversalRecordLocator", EmitDefaultValue = true)]
        public bool ContainsHealthUniversalRecordLocator { get; set; }

        /// <summary>
        /// True if the input contains biometric data references (e.g. fingerprints, retinal scans, voiceprints).
        /// </summary>
        /// <value>True if the input contains biometric data references (e.g. fingerprints, retinal scans, voiceprints).</value>
        [DataMember(Name = "ContainsBiometrics", EmitDefaultValue = true)]
        public bool ContainsBiometrics { get; set; }

        /// <summary>
        /// Rationale for why the conclusion was formed. Only populated when ProvideAnalysisRationale is set to true in the request.
        /// </summary>
        /// <value>Rationale for why the conclusion was formed. Only populated when ProvideAnalysisRationale is set to true in the request.</value>
        [DataMember(Name = "AnalysisRationale", EmitDefaultValue = false)]
        public string AnalysisRationale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DlpAdvancedDetectionResponse {\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ContainsEmailAddress: ").Append(ContainsEmailAddress).Append("\n");
            sb.Append("  ContainsPhoneNumber: ").Append(ContainsPhoneNumber).Append("\n");
            sb.Append("  ContainsStreetAddress: ").Append(ContainsStreetAddress).Append("\n");
            sb.Append("  ContainsPersonName: ").Append(ContainsPersonName).Append("\n");
            sb.Append("  ContainsBirthDate: ").Append(ContainsBirthDate).Append("\n");
            sb.Append("  ContainsPassportNumber: ").Append(ContainsPassportNumber).Append("\n");
            sb.Append("  ContainsDriversLicense: ").Append(ContainsDriversLicense).Append("\n");
            sb.Append("  ContainsSocialSecurityNumber: ").Append(ContainsSocialSecurityNumber).Append("\n");
            sb.Append("  ContainsTaxpayerID: ").Append(ContainsTaxpayerID).Append("\n");
            sb.Append("  ContainsCreditCardNumber: ").Append(ContainsCreditCardNumber).Append("\n");
            sb.Append("  ContainsCreditCardExpirationDate: ").Append(ContainsCreditCardExpirationDate).Append("\n");
            sb.Append("  ContainsCreditCardVerificationCode: ").Append(ContainsCreditCardVerificationCode).Append("\n");
            sb.Append("  ContainsBankAccountNumber: ").Append(ContainsBankAccountNumber).Append("\n");
            sb.Append("  ContainsIBAN: ").Append(ContainsIBAN).Append("\n");
            sb.Append("  ContainsHealthInsuranceNumber: ").Append(ContainsHealthInsuranceNumber).Append("\n");
            sb.Append("  ContainsBearerToken: ").Append(ContainsBearerToken).Append("\n");
            sb.Append("  ContainsHttpCookie: ").Append(ContainsHttpCookie).Append("\n");
            sb.Append("  ContainsPrivateKeys: ").Append(ContainsPrivateKeys).Append("\n");
            sb.Append("  ContainsCredentials: ").Append(ContainsCredentials).Append("\n");
            sb.Append("  ContainsDeepWebUrls: ").Append(ContainsDeepWebUrls).Append("\n");
            sb.Append("  ContainsSourceCode: ").Append(ContainsSourceCode).Append("\n");
            sb.Append("  ContainsIpAddress: ").Append(ContainsIpAddress).Append("\n");
            sb.Append("  ContainsMacAddress: ").Append(ContainsMacAddress).Append("\n");
            sb.Append("  ContainsHealthInsuranceMemberID: ").Append(ContainsHealthInsuranceMemberID).Append("\n");
            sb.Append("  ContainsHealthInjuryOrDisease: ").Append(ContainsHealthInjuryOrDisease).Append("\n");
            sb.Append("  ContainsHealthTypeOfTreatment: ").Append(ContainsHealthTypeOfTreatment).Append("\n");
            sb.Append("  ContainsHealthDateAndTimeOfTreatment: ").Append(ContainsHealthDateAndTimeOfTreatment).Append("\n");
            sb.Append("  ContainsHealthPlanBeneficiaryNumber: ").Append(ContainsHealthPlanBeneficiaryNumber).Append("\n");
            sb.Append("  ContainsHealthPaymentsMadeForTreatment: ").Append(ContainsHealthPaymentsMadeForTreatment).Append("\n");
            sb.Append("  ContainsFaces: ").Append(ContainsFaces).Append("\n");
            sb.Append("  ContainsVehicleID: ").Append(ContainsVehicleID).Append("\n");
            sb.Append("  ContainsDeviceID: ").Append(ContainsDeviceID).Append("\n");
            sb.Append("  ContainsNamesOfRelatives: ").Append(ContainsNamesOfRelatives).Append("\n");
            sb.Append("  ContainsHealthUniversalRecordLocator: ").Append(ContainsHealthUniversalRecordLocator).Append("\n");
            sb.Append("  ContainsBiometrics: ").Append(ContainsBiometrics).Append("\n");
            sb.Append("  AnalysisRationale: ").Append(AnalysisRationale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
