/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.DLP.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.DLP.Model
{
    /// <summary>
    /// Result of performing a DLP batch job operation
    /// </summary>
    [DataContract(Name = "DlpBatchJobStatusResult")]
    public partial class DlpBatchJobStatusResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlpBatchJobStatusResult" /> class.
        /// </summary>
        /// <param name="successful">True if the operation to check the status of the job was successful, false otherwise.</param>
        /// <param name="asyncJobStatus">Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED.</param>
        /// <param name="asyncJobID">Job ID.</param>
        /// <param name="detectAudioResult">detectAudioResult.</param>
        /// <param name="detectAudioAdvancedResult">detectAudioAdvancedResult.</param>
        /// <param name="redactAudioResult">redactAudioResult.</param>
        /// <param name="redactAudioAdvancedResult">redactAudioAdvancedResult.</param>
        /// <param name="errorMessage">Error message (if any).</param>
        public DlpBatchJobStatusResult(bool successful = default(bool), string asyncJobStatus = default(string), string asyncJobID = default(string), DlpAudioDetectionResponse detectAudioResult = default(DlpAudioDetectionResponse), DlpAdvancedAudioDetectionResponse detectAudioAdvancedResult = default(DlpAdvancedAudioDetectionResponse), DlpAudioRedactionResponse redactAudioResult = default(DlpAudioRedactionResponse), DlpAdvancedAudioRedactionResponse redactAudioAdvancedResult = default(DlpAdvancedAudioRedactionResponse), string errorMessage = default(string))
        {
            this.Successful = successful;
            this.AsyncJobStatus = asyncJobStatus;
            this.AsyncJobID = asyncJobID;
            this.DetectAudioResult = detectAudioResult;
            this.DetectAudioAdvancedResult = detectAudioAdvancedResult;
            this.RedactAudioResult = redactAudioResult;
            this.RedactAudioAdvancedResult = redactAudioAdvancedResult;
            this.ErrorMessage = errorMessage;
        }

        /// <summary>
        /// True if the operation to check the status of the job was successful, false otherwise
        /// </summary>
        /// <value>True if the operation to check the status of the job was successful, false otherwise</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED
        /// </summary>
        /// <value>Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED</value>
        [DataMember(Name = "AsyncJobStatus", EmitDefaultValue = false)]
        public string AsyncJobStatus { get; set; }

        /// <summary>
        /// Job ID
        /// </summary>
        /// <value>Job ID</value>
        [DataMember(Name = "AsyncJobID", EmitDefaultValue = false)]
        public string AsyncJobID { get; set; }

        /// <summary>
        /// Gets or Sets DetectAudioResult
        /// </summary>
        [DataMember(Name = "DetectAudioResult", EmitDefaultValue = false)]
        public DlpAudioDetectionResponse DetectAudioResult { get; set; }

        /// <summary>
        /// Gets or Sets DetectAudioAdvancedResult
        /// </summary>
        [DataMember(Name = "DetectAudioAdvancedResult", EmitDefaultValue = false)]
        public DlpAdvancedAudioDetectionResponse DetectAudioAdvancedResult { get; set; }

        /// <summary>
        /// Gets or Sets RedactAudioResult
        /// </summary>
        [DataMember(Name = "RedactAudioResult", EmitDefaultValue = false)]
        public DlpAudioRedactionResponse RedactAudioResult { get; set; }

        /// <summary>
        /// Gets or Sets RedactAudioAdvancedResult
        /// </summary>
        [DataMember(Name = "RedactAudioAdvancedResult", EmitDefaultValue = false)]
        public DlpAdvancedAudioRedactionResponse RedactAudioAdvancedResult { get; set; }

        /// <summary>
        /// Error message (if any)
        /// </summary>
        /// <value>Error message (if any)</value>
        [DataMember(Name = "ErrorMessage", EmitDefaultValue = false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DlpBatchJobStatusResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  AsyncJobStatus: ").Append(AsyncJobStatus).Append("\n");
            sb.Append("  AsyncJobID: ").Append(AsyncJobID).Append("\n");
            sb.Append("  DetectAudioResult: ").Append(DetectAudioResult).Append("\n");
            sb.Append("  DetectAudioAdvancedResult: ").Append(DetectAudioAdvancedResult).Append("\n");
            sb.Append("  RedactAudioResult: ").Append(RedactAudioResult).Append("\n");
            sb.Append("  RedactAudioAdvancedResult: ").Append(RedactAudioAdvancedResult).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
