/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.DLP.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.DLP.Model
{
    /// <summary>
    /// Request object for DLP document detection with 23 PII detection types.
    /// </summary>
    [DataContract(Name = "DlpDocumentDetectionRequest")]
    public partial class DlpDocumentDetectionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlpDocumentDetectionRequest" /> class.
        /// </summary>
        /// <param name="inputFile">Document file bytes (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, or WEBP) to scan for PII and sensitive data..</param>
        /// <param name="fileName">Optional. Name of the input file including extension, used for format detection. If not provided, format is detected from file contents..</param>
        /// <param name="recognitionMode">Optional. Recognition mode for image processing. Options: null (default), \&quot;Fast\&quot;, \&quot;FastPlus\&quot;, \&quot;FastMini\&quot;..</param>
        /// <param name="allowEmailAddress">Set to true to allow email addresses in the document and not flag them as PII..</param>
        /// <param name="allowPhoneNumber">Set to true to allow phone numbers in the document and not flag them as PII..</param>
        /// <param name="allowStreetAddress">Set to true to allow street addresses in the document and not flag them as PII..</param>
        /// <param name="allowPersonName">Set to true to allow person names in the document and not flag them as PII..</param>
        /// <param name="allowBirthDate">Set to true to allow birth dates in the document and not flag them as PII..</param>
        /// <param name="allowPassportNumber">Set to true to allow passport numbers in the document and not flag them as PII..</param>
        /// <param name="allowDriversLicense">Set to true to allow drivers license numbers in the document and not flag them as PII..</param>
        /// <param name="allowSocialSecurityNumber">Set to true to allow social security numbers in the document and not flag them as PII..</param>
        /// <param name="allowTaxpayerID">Set to true to allow taxpayer IDs in the document and not flag them as PII..</param>
        /// <param name="allowCreditCardNumber">Set to true to allow credit card numbers in the document and not flag them as PII..</param>
        /// <param name="allowCreditCardExpirationDate">Set to true to allow credit card expiration dates in the document and not flag them as PII..</param>
        /// <param name="allowCreditCardVerificationCode">Set to true to allow credit card verification codes in the document and not flag them as PII..</param>
        /// <param name="allowBankAccountNumber">Set to true to allow bank account numbers in the document and not flag them as PII..</param>
        /// <param name="allowIBAN">Set to true to allow IBANs in the document and not flag them as PII..</param>
        /// <param name="allowHealthInsuranceNumber">Set to true to allow health insurance numbers in the document and not flag them as PII..</param>
        /// <param name="allowBearerToken">Set to true to allow bearer tokens in the document and not flag them as PII..</param>
        /// <param name="allowHttpCookie">Set to true to allow HTTP cookies in the document and not flag them as PII..</param>
        /// <param name="allowPrivateKeys">Set to true to allow private keys in the document and not flag them as PII..</param>
        /// <param name="allowCredentials">Set to true to allow credentials (usernames/passwords) in the document and not flag them as PII..</param>
        /// <param name="allowDeepWebUrls">Set to true to allow deep web URLs (.onion) in the document and not flag them as PII..</param>
        /// <param name="allowSourceCode">Set to true to allow source code in the document and not flag it as sensitive data..</param>
        /// <param name="allowIpAddress">Set to true to allow IP addresses in the document and not flag them as PII..</param>
        /// <param name="allowMacAddress">Set to true to allow MAC addresses in the document and not flag them as PII..</param>
        public DlpDocumentDetectionRequest(byte[] inputFile = default(byte[]), string fileName = default(string), string recognitionMode = default(string), bool allowEmailAddress = default(bool), bool allowPhoneNumber = default(bool), bool allowStreetAddress = default(bool), bool allowPersonName = default(bool), bool allowBirthDate = default(bool), bool allowPassportNumber = default(bool), bool allowDriversLicense = default(bool), bool allowSocialSecurityNumber = default(bool), bool allowTaxpayerID = default(bool), bool allowCreditCardNumber = default(bool), bool allowCreditCardExpirationDate = default(bool), bool allowCreditCardVerificationCode = default(bool), bool allowBankAccountNumber = default(bool), bool allowIBAN = default(bool), bool allowHealthInsuranceNumber = default(bool), bool allowBearerToken = default(bool), bool allowHttpCookie = default(bool), bool allowPrivateKeys = default(bool), bool allowCredentials = default(bool), bool allowDeepWebUrls = default(bool), bool allowSourceCode = default(bool), bool allowIpAddress = default(bool), bool allowMacAddress = default(bool))
        {
            this.InputFile = inputFile;
            this.FileName = fileName;
            this.RecognitionMode = recognitionMode;
            this.AllowEmailAddress = allowEmailAddress;
            this.AllowPhoneNumber = allowPhoneNumber;
            this.AllowStreetAddress = allowStreetAddress;
            this.AllowPersonName = allowPersonName;
            this.AllowBirthDate = allowBirthDate;
            this.AllowPassportNumber = allowPassportNumber;
            this.AllowDriversLicense = allowDriversLicense;
            this.AllowSocialSecurityNumber = allowSocialSecurityNumber;
            this.AllowTaxpayerID = allowTaxpayerID;
            this.AllowCreditCardNumber = allowCreditCardNumber;
            this.AllowCreditCardExpirationDate = allowCreditCardExpirationDate;
            this.AllowCreditCardVerificationCode = allowCreditCardVerificationCode;
            this.AllowBankAccountNumber = allowBankAccountNumber;
            this.AllowIBAN = allowIBAN;
            this.AllowHealthInsuranceNumber = allowHealthInsuranceNumber;
            this.AllowBearerToken = allowBearerToken;
            this.AllowHttpCookie = allowHttpCookie;
            this.AllowPrivateKeys = allowPrivateKeys;
            this.AllowCredentials = allowCredentials;
            this.AllowDeepWebUrls = allowDeepWebUrls;
            this.AllowSourceCode = allowSourceCode;
            this.AllowIpAddress = allowIpAddress;
            this.AllowMacAddress = allowMacAddress;
        }

        /// <summary>
        /// Document file bytes (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, or WEBP) to scan for PII and sensitive data.
        /// </summary>
        /// <value>Document file bytes (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, or WEBP) to scan for PII and sensitive data.</value>
        [DataMember(Name = "InputFile", EmitDefaultValue = false)]
        public byte[] InputFile { get; set; }

        /// <summary>
        /// Optional. Name of the input file including extension, used for format detection. If not provided, format is detected from file contents.
        /// </summary>
        /// <value>Optional. Name of the input file including extension, used for format detection. If not provided, format is detected from file contents.</value>
        /*
        <example>input.pdf</example>
        */
        [DataMember(Name = "FileName", EmitDefaultValue = false)]
        public string FileName { get; set; }

        /// <summary>
        /// Optional. Recognition mode for image processing. Options: null (default), \&quot;Fast\&quot;, \&quot;FastPlus\&quot;, \&quot;FastMini\&quot;.
        /// </summary>
        /// <value>Optional. Recognition mode for image processing. Options: null (default), \&quot;Fast\&quot;, \&quot;FastPlus\&quot;, \&quot;FastMini\&quot;.</value>
        [DataMember(Name = "RecognitionMode", EmitDefaultValue = false)]
        public string RecognitionMode { get; set; }

        /// <summary>
        /// Set to true to allow email addresses in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow email addresses in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowEmailAddress", EmitDefaultValue = true)]
        public bool AllowEmailAddress { get; set; }

        /// <summary>
        /// Set to true to allow phone numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow phone numbers in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPhoneNumber", EmitDefaultValue = true)]
        public bool AllowPhoneNumber { get; set; }

        /// <summary>
        /// Set to true to allow street addresses in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow street addresses in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowStreetAddress", EmitDefaultValue = true)]
        public bool AllowStreetAddress { get; set; }

        /// <summary>
        /// Set to true to allow person names in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow person names in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPersonName", EmitDefaultValue = true)]
        public bool AllowPersonName { get; set; }

        /// <summary>
        /// Set to true to allow birth dates in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow birth dates in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowBirthDate", EmitDefaultValue = true)]
        public bool AllowBirthDate { get; set; }

        /// <summary>
        /// Set to true to allow passport numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow passport numbers in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPassportNumber", EmitDefaultValue = true)]
        public bool AllowPassportNumber { get; set; }

        /// <summary>
        /// Set to true to allow drivers license numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow drivers license numbers in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowDriversLicense", EmitDefaultValue = true)]
        public bool AllowDriversLicense { get; set; }

        /// <summary>
        /// Set to true to allow social security numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow social security numbers in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowSocialSecurityNumber", EmitDefaultValue = true)]
        public bool AllowSocialSecurityNumber { get; set; }

        /// <summary>
        /// Set to true to allow taxpayer IDs in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow taxpayer IDs in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowTaxpayerID", EmitDefaultValue = true)]
        public bool AllowTaxpayerID { get; set; }

        /// <summary>
        /// Set to true to allow credit card numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credit card numbers in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowCreditCardNumber", EmitDefaultValue = true)]
        public bool AllowCreditCardNumber { get; set; }

        /// <summary>
        /// Set to true to allow credit card expiration dates in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credit card expiration dates in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowCreditCardExpirationDate", EmitDefaultValue = true)]
        public bool AllowCreditCardExpirationDate { get; set; }

        /// <summary>
        /// Set to true to allow credit card verification codes in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credit card verification codes in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowCreditCardVerificationCode", EmitDefaultValue = true)]
        public bool AllowCreditCardVerificationCode { get; set; }

        /// <summary>
        /// Set to true to allow bank account numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow bank account numbers in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowBankAccountNumber", EmitDefaultValue = true)]
        public bool AllowBankAccountNumber { get; set; }

        /// <summary>
        /// Set to true to allow IBANs in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow IBANs in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowIBAN", EmitDefaultValue = true)]
        public bool AllowIBAN { get; set; }

        /// <summary>
        /// Set to true to allow health insurance numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow health insurance numbers in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthInsuranceNumber", EmitDefaultValue = true)]
        public bool AllowHealthInsuranceNumber { get; set; }

        /// <summary>
        /// Set to true to allow bearer tokens in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow bearer tokens in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowBearerToken", EmitDefaultValue = true)]
        public bool AllowBearerToken { get; set; }

        /// <summary>
        /// Set to true to allow HTTP cookies in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow HTTP cookies in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHttpCookie", EmitDefaultValue = true)]
        public bool AllowHttpCookie { get; set; }

        /// <summary>
        /// Set to true to allow private keys in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow private keys in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPrivateKeys", EmitDefaultValue = true)]
        public bool AllowPrivateKeys { get; set; }

        /// <summary>
        /// Set to true to allow credentials (usernames/passwords) in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credentials (usernames/passwords) in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowCredentials", EmitDefaultValue = true)]
        public bool AllowCredentials { get; set; }

        /// <summary>
        /// Set to true to allow deep web URLs (.onion) in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow deep web URLs (.onion) in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowDeepWebUrls", EmitDefaultValue = true)]
        public bool AllowDeepWebUrls { get; set; }

        /// <summary>
        /// Set to true to allow source code in the document and not flag it as sensitive data.
        /// </summary>
        /// <value>Set to true to allow source code in the document and not flag it as sensitive data.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowSourceCode", EmitDefaultValue = true)]
        public bool AllowSourceCode { get; set; }

        /// <summary>
        /// Set to true to allow IP addresses in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow IP addresses in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowIpAddress", EmitDefaultValue = true)]
        public bool AllowIpAddress { get; set; }

        /// <summary>
        /// Set to true to allow MAC addresses in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow MAC addresses in the document and not flag them as PII.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowMacAddress", EmitDefaultValue = true)]
        public bool AllowMacAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DlpDocumentDetectionRequest {\n");
            sb.Append("  InputFile: ").Append(InputFile).Append("\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  RecognitionMode: ").Append(RecognitionMode).Append("\n");
            sb.Append("  AllowEmailAddress: ").Append(AllowEmailAddress).Append("\n");
            sb.Append("  AllowPhoneNumber: ").Append(AllowPhoneNumber).Append("\n");
            sb.Append("  AllowStreetAddress: ").Append(AllowStreetAddress).Append("\n");
            sb.Append("  AllowPersonName: ").Append(AllowPersonName).Append("\n");
            sb.Append("  AllowBirthDate: ").Append(AllowBirthDate).Append("\n");
            sb.Append("  AllowPassportNumber: ").Append(AllowPassportNumber).Append("\n");
            sb.Append("  AllowDriversLicense: ").Append(AllowDriversLicense).Append("\n");
            sb.Append("  AllowSocialSecurityNumber: ").Append(AllowSocialSecurityNumber).Append("\n");
            sb.Append("  AllowTaxpayerID: ").Append(AllowTaxpayerID).Append("\n");
            sb.Append("  AllowCreditCardNumber: ").Append(AllowCreditCardNumber).Append("\n");
            sb.Append("  AllowCreditCardExpirationDate: ").Append(AllowCreditCardExpirationDate).Append("\n");
            sb.Append("  AllowCreditCardVerificationCode: ").Append(AllowCreditCardVerificationCode).Append("\n");
            sb.Append("  AllowBankAccountNumber: ").Append(AllowBankAccountNumber).Append("\n");
            sb.Append("  AllowIBAN: ").Append(AllowIBAN).Append("\n");
            sb.Append("  AllowHealthInsuranceNumber: ").Append(AllowHealthInsuranceNumber).Append("\n");
            sb.Append("  AllowBearerToken: ").Append(AllowBearerToken).Append("\n");
            sb.Append("  AllowHttpCookie: ").Append(AllowHttpCookie).Append("\n");
            sb.Append("  AllowPrivateKeys: ").Append(AllowPrivateKeys).Append("\n");
            sb.Append("  AllowCredentials: ").Append(AllowCredentials).Append("\n");
            sb.Append("  AllowDeepWebUrls: ").Append(AllowDeepWebUrls).Append("\n");
            sb.Append("  AllowSourceCode: ").Append(AllowSourceCode).Append("\n");
            sb.Append("  AllowIpAddress: ").Append(AllowIpAddress).Append("\n");
            sb.Append("  AllowMacAddress: ").Append(AllowMacAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
