/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.DLP.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.DLP.Model
{
    /// <summary>
    /// Response object for DLP document redaction with 23 PII detection results and redacted document.
    /// </summary>
    [DataContract(Name = "DlpDocumentRedactionResponse")]
    public partial class DlpDocumentRedactionResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlpDocumentRedactionResponse" /> class.
        /// </summary>
        /// <param name="redactedDocument">The redacted document as a rasterized PDF with PII regions blurred, or the original file if no disallowed PII was found..</param>
        /// <param name="cleanResult">True if no disallowed PII or sensitive data types were detected; false if any disallowed type was found and redacted..</param>
        /// <param name="containsEmailAddress">True if the document contains email addresses..</param>
        /// <param name="containsPhoneNumber">True if the document contains phone numbers..</param>
        /// <param name="containsStreetAddress">True if the document contains street addresses..</param>
        /// <param name="containsPersonName">True if the document contains person names..</param>
        /// <param name="containsBirthDate">True if the document contains birth dates..</param>
        /// <param name="containsPassportNumber">True if the document contains passport numbers..</param>
        /// <param name="containsDriversLicense">True if the document contains drivers license numbers..</param>
        /// <param name="containsSocialSecurityNumber">True if the document contains social security numbers..</param>
        /// <param name="containsTaxpayerID">True if the document contains taxpayer IDs..</param>
        /// <param name="containsCreditCardNumber">True if the document contains credit card numbers..</param>
        /// <param name="containsCreditCardExpirationDate">True if the document contains credit card expiration dates..</param>
        /// <param name="containsCreditCardVerificationCode">True if the document contains credit card verification codes..</param>
        /// <param name="containsBankAccountNumber">True if the document contains bank account numbers..</param>
        /// <param name="containsIBAN">True if the document contains IBANs..</param>
        /// <param name="containsHealthInsuranceNumber">True if the document contains health insurance numbers..</param>
        /// <param name="containsBearerToken">True if the document contains bearer tokens..</param>
        /// <param name="containsHttpCookie">True if the document contains HTTP cookies..</param>
        /// <param name="containsPrivateKeys">True if the document contains private keys..</param>
        /// <param name="containsCredentials">True if the document contains credentials (usernames/passwords)..</param>
        /// <param name="containsDeepWebUrls">True if the document contains deep web URLs (.onion)..</param>
        /// <param name="containsSourceCode">True if the document contains source code..</param>
        /// <param name="containsIpAddress">True if the document contains IP addresses..</param>
        /// <param name="containsMacAddress">True if the document contains MAC addresses..</param>
        /// <param name="pagesRedacted">List of pages that were redacted (had PII regions blurred)..</param>
        public DlpDocumentRedactionResponse(byte[] redactedDocument = default(byte[]), bool cleanResult = default(bool), bool containsEmailAddress = default(bool), bool containsPhoneNumber = default(bool), bool containsStreetAddress = default(bool), bool containsPersonName = default(bool), bool containsBirthDate = default(bool), bool containsPassportNumber = default(bool), bool containsDriversLicense = default(bool), bool containsSocialSecurityNumber = default(bool), bool containsTaxpayerID = default(bool), bool containsCreditCardNumber = default(bool), bool containsCreditCardExpirationDate = default(bool), bool containsCreditCardVerificationCode = default(bool), bool containsBankAccountNumber = default(bool), bool containsIBAN = default(bool), bool containsHealthInsuranceNumber = default(bool), bool containsBearerToken = default(bool), bool containsHttpCookie = default(bool), bool containsPrivateKeys = default(bool), bool containsCredentials = default(bool), bool containsDeepWebUrls = default(bool), bool containsSourceCode = default(bool), bool containsIpAddress = default(bool), bool containsMacAddress = default(bool), List<RedactedPageInfo> pagesRedacted = default(List<RedactedPageInfo>))
        {
            this.RedactedDocument = redactedDocument;
            this.CleanResult = cleanResult;
            this.ContainsEmailAddress = containsEmailAddress;
            this.ContainsPhoneNumber = containsPhoneNumber;
            this.ContainsStreetAddress = containsStreetAddress;
            this.ContainsPersonName = containsPersonName;
            this.ContainsBirthDate = containsBirthDate;
            this.ContainsPassportNumber = containsPassportNumber;
            this.ContainsDriversLicense = containsDriversLicense;
            this.ContainsSocialSecurityNumber = containsSocialSecurityNumber;
            this.ContainsTaxpayerID = containsTaxpayerID;
            this.ContainsCreditCardNumber = containsCreditCardNumber;
            this.ContainsCreditCardExpirationDate = containsCreditCardExpirationDate;
            this.ContainsCreditCardVerificationCode = containsCreditCardVerificationCode;
            this.ContainsBankAccountNumber = containsBankAccountNumber;
            this.ContainsIBAN = containsIBAN;
            this.ContainsHealthInsuranceNumber = containsHealthInsuranceNumber;
            this.ContainsBearerToken = containsBearerToken;
            this.ContainsHttpCookie = containsHttpCookie;
            this.ContainsPrivateKeys = containsPrivateKeys;
            this.ContainsCredentials = containsCredentials;
            this.ContainsDeepWebUrls = containsDeepWebUrls;
            this.ContainsSourceCode = containsSourceCode;
            this.ContainsIpAddress = containsIpAddress;
            this.ContainsMacAddress = containsMacAddress;
            this.PagesRedacted = pagesRedacted;
        }

        /// <summary>
        /// The redacted document as a rasterized PDF with PII regions blurred, or the original file if no disallowed PII was found.
        /// </summary>
        /// <value>The redacted document as a rasterized PDF with PII regions blurred, or the original file if no disallowed PII was found.</value>
        [DataMember(Name = "RedactedDocument", EmitDefaultValue = false)]
        public byte[] RedactedDocument { get; set; }

        /// <summary>
        /// True if no disallowed PII or sensitive data types were detected; false if any disallowed type was found and redacted.
        /// </summary>
        /// <value>True if no disallowed PII or sensitive data types were detected; false if any disallowed type was found and redacted.</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// True if the document contains email addresses.
        /// </summary>
        /// <value>True if the document contains email addresses.</value>
        [DataMember(Name = "ContainsEmailAddress", EmitDefaultValue = true)]
        public bool ContainsEmailAddress { get; set; }

        /// <summary>
        /// True if the document contains phone numbers.
        /// </summary>
        /// <value>True if the document contains phone numbers.</value>
        [DataMember(Name = "ContainsPhoneNumber", EmitDefaultValue = true)]
        public bool ContainsPhoneNumber { get; set; }

        /// <summary>
        /// True if the document contains street addresses.
        /// </summary>
        /// <value>True if the document contains street addresses.</value>
        [DataMember(Name = "ContainsStreetAddress", EmitDefaultValue = true)]
        public bool ContainsStreetAddress { get; set; }

        /// <summary>
        /// True if the document contains person names.
        /// </summary>
        /// <value>True if the document contains person names.</value>
        [DataMember(Name = "ContainsPersonName", EmitDefaultValue = true)]
        public bool ContainsPersonName { get; set; }

        /// <summary>
        /// True if the document contains birth dates.
        /// </summary>
        /// <value>True if the document contains birth dates.</value>
        [DataMember(Name = "ContainsBirthDate", EmitDefaultValue = true)]
        public bool ContainsBirthDate { get; set; }

        /// <summary>
        /// True if the document contains passport numbers.
        /// </summary>
        /// <value>True if the document contains passport numbers.</value>
        [DataMember(Name = "ContainsPassportNumber", EmitDefaultValue = true)]
        public bool ContainsPassportNumber { get; set; }

        /// <summary>
        /// True if the document contains drivers license numbers.
        /// </summary>
        /// <value>True if the document contains drivers license numbers.</value>
        [DataMember(Name = "ContainsDriversLicense", EmitDefaultValue = true)]
        public bool ContainsDriversLicense { get; set; }

        /// <summary>
        /// True if the document contains social security numbers.
        /// </summary>
        /// <value>True if the document contains social security numbers.</value>
        [DataMember(Name = "ContainsSocialSecurityNumber", EmitDefaultValue = true)]
        public bool ContainsSocialSecurityNumber { get; set; }

        /// <summary>
        /// True if the document contains taxpayer IDs.
        /// </summary>
        /// <value>True if the document contains taxpayer IDs.</value>
        [DataMember(Name = "ContainsTaxpayerID", EmitDefaultValue = true)]
        public bool ContainsTaxpayerID { get; set; }

        /// <summary>
        /// True if the document contains credit card numbers.
        /// </summary>
        /// <value>True if the document contains credit card numbers.</value>
        [DataMember(Name = "ContainsCreditCardNumber", EmitDefaultValue = true)]
        public bool ContainsCreditCardNumber { get; set; }

        /// <summary>
        /// True if the document contains credit card expiration dates.
        /// </summary>
        /// <value>True if the document contains credit card expiration dates.</value>
        [DataMember(Name = "ContainsCreditCardExpirationDate", EmitDefaultValue = true)]
        public bool ContainsCreditCardExpirationDate { get; set; }

        /// <summary>
        /// True if the document contains credit card verification codes.
        /// </summary>
        /// <value>True if the document contains credit card verification codes.</value>
        [DataMember(Name = "ContainsCreditCardVerificationCode", EmitDefaultValue = true)]
        public bool ContainsCreditCardVerificationCode { get; set; }

        /// <summary>
        /// True if the document contains bank account numbers.
        /// </summary>
        /// <value>True if the document contains bank account numbers.</value>
        [DataMember(Name = "ContainsBankAccountNumber", EmitDefaultValue = true)]
        public bool ContainsBankAccountNumber { get; set; }

        /// <summary>
        /// True if the document contains IBANs.
        /// </summary>
        /// <value>True if the document contains IBANs.</value>
        [DataMember(Name = "ContainsIBAN", EmitDefaultValue = true)]
        public bool ContainsIBAN { get; set; }

        /// <summary>
        /// True if the document contains health insurance numbers.
        /// </summary>
        /// <value>True if the document contains health insurance numbers.</value>
        [DataMember(Name = "ContainsHealthInsuranceNumber", EmitDefaultValue = true)]
        public bool ContainsHealthInsuranceNumber { get; set; }

        /// <summary>
        /// True if the document contains bearer tokens.
        /// </summary>
        /// <value>True if the document contains bearer tokens.</value>
        [DataMember(Name = "ContainsBearerToken", EmitDefaultValue = true)]
        public bool ContainsBearerToken { get; set; }

        /// <summary>
        /// True if the document contains HTTP cookies.
        /// </summary>
        /// <value>True if the document contains HTTP cookies.</value>
        [DataMember(Name = "ContainsHttpCookie", EmitDefaultValue = true)]
        public bool ContainsHttpCookie { get; set; }

        /// <summary>
        /// True if the document contains private keys.
        /// </summary>
        /// <value>True if the document contains private keys.</value>
        [DataMember(Name = "ContainsPrivateKeys", EmitDefaultValue = true)]
        public bool ContainsPrivateKeys { get; set; }

        /// <summary>
        /// True if the document contains credentials (usernames/passwords).
        /// </summary>
        /// <value>True if the document contains credentials (usernames/passwords).</value>
        [DataMember(Name = "ContainsCredentials", EmitDefaultValue = true)]
        public bool ContainsCredentials { get; set; }

        /// <summary>
        /// True if the document contains deep web URLs (.onion).
        /// </summary>
        /// <value>True if the document contains deep web URLs (.onion).</value>
        [DataMember(Name = "ContainsDeepWebUrls", EmitDefaultValue = true)]
        public bool ContainsDeepWebUrls { get; set; }

        /// <summary>
        /// True if the document contains source code.
        /// </summary>
        /// <value>True if the document contains source code.</value>
        [DataMember(Name = "ContainsSourceCode", EmitDefaultValue = true)]
        public bool ContainsSourceCode { get; set; }

        /// <summary>
        /// True if the document contains IP addresses.
        /// </summary>
        /// <value>True if the document contains IP addresses.</value>
        [DataMember(Name = "ContainsIpAddress", EmitDefaultValue = true)]
        public bool ContainsIpAddress { get; set; }

        /// <summary>
        /// True if the document contains MAC addresses.
        /// </summary>
        /// <value>True if the document contains MAC addresses.</value>
        [DataMember(Name = "ContainsMacAddress", EmitDefaultValue = true)]
        public bool ContainsMacAddress { get; set; }

        /// <summary>
        /// List of pages that were redacted (had PII regions blurred).
        /// </summary>
        /// <value>List of pages that were redacted (had PII regions blurred).</value>
        [DataMember(Name = "PagesRedacted", EmitDefaultValue = false)]
        public List<RedactedPageInfo> PagesRedacted { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DlpDocumentRedactionResponse {\n");
            sb.Append("  RedactedDocument: ").Append(RedactedDocument).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ContainsEmailAddress: ").Append(ContainsEmailAddress).Append("\n");
            sb.Append("  ContainsPhoneNumber: ").Append(ContainsPhoneNumber).Append("\n");
            sb.Append("  ContainsStreetAddress: ").Append(ContainsStreetAddress).Append("\n");
            sb.Append("  ContainsPersonName: ").Append(ContainsPersonName).Append("\n");
            sb.Append("  ContainsBirthDate: ").Append(ContainsBirthDate).Append("\n");
            sb.Append("  ContainsPassportNumber: ").Append(ContainsPassportNumber).Append("\n");
            sb.Append("  ContainsDriversLicense: ").Append(ContainsDriversLicense).Append("\n");
            sb.Append("  ContainsSocialSecurityNumber: ").Append(ContainsSocialSecurityNumber).Append("\n");
            sb.Append("  ContainsTaxpayerID: ").Append(ContainsTaxpayerID).Append("\n");
            sb.Append("  ContainsCreditCardNumber: ").Append(ContainsCreditCardNumber).Append("\n");
            sb.Append("  ContainsCreditCardExpirationDate: ").Append(ContainsCreditCardExpirationDate).Append("\n");
            sb.Append("  ContainsCreditCardVerificationCode: ").Append(ContainsCreditCardVerificationCode).Append("\n");
            sb.Append("  ContainsBankAccountNumber: ").Append(ContainsBankAccountNumber).Append("\n");
            sb.Append("  ContainsIBAN: ").Append(ContainsIBAN).Append("\n");
            sb.Append("  ContainsHealthInsuranceNumber: ").Append(ContainsHealthInsuranceNumber).Append("\n");
            sb.Append("  ContainsBearerToken: ").Append(ContainsBearerToken).Append("\n");
            sb.Append("  ContainsHttpCookie: ").Append(ContainsHttpCookie).Append("\n");
            sb.Append("  ContainsPrivateKeys: ").Append(ContainsPrivateKeys).Append("\n");
            sb.Append("  ContainsCredentials: ").Append(ContainsCredentials).Append("\n");
            sb.Append("  ContainsDeepWebUrls: ").Append(ContainsDeepWebUrls).Append("\n");
            sb.Append("  ContainsSourceCode: ").Append(ContainsSourceCode).Append("\n");
            sb.Append("  ContainsIpAddress: ").Append(ContainsIpAddress).Append("\n");
            sb.Append("  ContainsMacAddress: ").Append(ContainsMacAddress).Append("\n");
            sb.Append("  PagesRedacted: ").Append(PagesRedacted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
