/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.DLP.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.DLP.Model
{
    /// <summary>
    /// Represents a time range in the audio that was redacted.
    /// </summary>
    [DataContract(Name = "RedactedAudioSegment")]
    public partial class RedactedAudioSegment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RedactedAudioSegment" /> class.
        /// </summary>
        /// <param name="startTimeMs">Start time of the redacted segment in the audio, in milliseconds..</param>
        /// <param name="endTimeMs">End time of the redacted segment in the audio, in milliseconds..</param>
        /// <param name="redactedText">The original text that was redacted in this segment..</param>
        public RedactedAudioSegment(long startTimeMs = default(long), long endTimeMs = default(long), string redactedText = default(string))
        {
            this.StartTimeMs = startTimeMs;
            this.EndTimeMs = endTimeMs;
            this.RedactedText = redactedText;
        }

        /// <summary>
        /// Start time of the redacted segment in the audio, in milliseconds.
        /// </summary>
        /// <value>Start time of the redacted segment in the audio, in milliseconds.</value>
        [DataMember(Name = "StartTimeMs", EmitDefaultValue = false)]
        public long StartTimeMs { get; set; }

        /// <summary>
        /// End time of the redacted segment in the audio, in milliseconds.
        /// </summary>
        /// <value>End time of the redacted segment in the audio, in milliseconds.</value>
        [DataMember(Name = "EndTimeMs", EmitDefaultValue = false)]
        public long EndTimeMs { get; set; }

        /// <summary>
        /// The original text that was redacted in this segment.
        /// </summary>
        /// <value>The original text that was redacted in this segment.</value>
        [DataMember(Name = "RedactedText", EmitDefaultValue = false)]
        public string RedactedText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RedactedAudioSegment {\n");
            sb.Append("  StartTimeMs: ").Append(StartTimeMs).Append("\n");
            sb.Append("  EndTimeMs: ").Append(EndTimeMs).Append("\n");
            sb.Append("  RedactedText: ").Append(RedactedText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
