/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.DLP.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.DLP.Model
{
    /// <summary>
    /// Information about a redacted page.
    /// </summary>
    [DataContract(Name = "RedactedPageInfo")]
    public partial class RedactedPageInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RedactedPageInfo" /> class.
        /// </summary>
        /// <param name="pageNumber">1-based page number that was redacted..</param>
        public RedactedPageInfo(int pageNumber = default(int))
        {
            this.PageNumber = pageNumber;
        }

        /// <summary>
        /// 1-based page number that was redacted.
        /// </summary>
        /// <value>1-based page number that was redacted.</value>
        [DataMember(Name = "PageNumber", EmitDefaultValue = false)]
        public int PageNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RedactedPageInfo {\n");
            sb.Append("  PageNumber: ").Append(PageNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
