/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Cloudmersive.APIClient.NET.DLP.Client;
using Cloudmersive.APIClient.NET.DLP.Model;

namespace Cloudmersive.APIClient.NET.DLP.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDetectApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Detect User Data in Document Image
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpDetectionResponse</returns>
        DlpDetectionResponse DetectDocument(DlpDocumentDetectionRequest body = default(DlpDocumentDetectionRequest), int operationIndex = 0);

        /// <summary>
        /// Detect User Data in Document Image
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpDetectionResponse</returns>
        ApiResponse<DlpDetectionResponse> DetectDocumentWithHttpInfo(DlpDocumentDetectionRequest body = default(DlpDocumentDetectionRequest), int operationIndex = 0);
        /// <summary>
        /// Detect User Data in Document Image (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpAdvancedDetectionResponse</returns>
        DlpAdvancedDetectionResponse DetectDocumentAdvanced(DlpAdvancedDocumentDetectionRequest body = default(DlpAdvancedDocumentDetectionRequest), int operationIndex = 0);

        /// <summary>
        /// Detect User Data in Document Image (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpAdvancedDetectionResponse</returns>
        ApiResponse<DlpAdvancedDetectionResponse> DetectDocumentAdvancedWithHttpInfo(DlpAdvancedDocumentDetectionRequest body = default(DlpAdvancedDocumentDetectionRequest), int operationIndex = 0);
        /// <summary>
        /// Detect User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpDetectionResponse</returns>
        DlpDetectionResponse DetectText(DlpDetectionRequest body = default(DlpDetectionRequest), int operationIndex = 0);

        /// <summary>
        /// Detect User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpDetectionResponse</returns>
        ApiResponse<DlpDetectionResponse> DetectTextWithHttpInfo(DlpDetectionRequest body = default(DlpDetectionRequest), int operationIndex = 0);
        /// <summary>
        /// Detect User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpAdvancedDetectionResponse</returns>
        DlpAdvancedDetectionResponse DetectTextAdvanced(DlpAdvancedDetectionRequest body = default(DlpAdvancedDetectionRequest), int operationIndex = 0);

        /// <summary>
        /// Detect User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpAdvancedDetectionResponse</returns>
        ApiResponse<DlpAdvancedDetectionResponse> DetectTextAdvancedWithHttpInfo(DlpAdvancedDetectionRequest body = default(DlpAdvancedDetectionRequest), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDetectApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Detect User Data in Document Image
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpDetectionResponse</returns>
        System.Threading.Tasks.Task<DlpDetectionResponse> DetectDocumentAsync(DlpDocumentDetectionRequest body = default(DlpDocumentDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Detect User Data in Document Image
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpDetectionResponse>> DetectDocumentWithHttpInfoAsync(DlpDocumentDetectionRequest body = default(DlpDocumentDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Detect User Data in Document Image (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpAdvancedDetectionResponse</returns>
        System.Threading.Tasks.Task<DlpAdvancedDetectionResponse> DetectDocumentAdvancedAsync(DlpAdvancedDocumentDetectionRequest body = default(DlpAdvancedDocumentDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Detect User Data in Document Image (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpAdvancedDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpAdvancedDetectionResponse>> DetectDocumentAdvancedWithHttpInfoAsync(DlpAdvancedDocumentDetectionRequest body = default(DlpAdvancedDocumentDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Detect User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpDetectionResponse</returns>
        System.Threading.Tasks.Task<DlpDetectionResponse> DetectTextAsync(DlpDetectionRequest body = default(DlpDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Detect User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpDetectionResponse>> DetectTextWithHttpInfoAsync(DlpDetectionRequest body = default(DlpDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Detect User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpAdvancedDetectionResponse</returns>
        System.Threading.Tasks.Task<DlpAdvancedDetectionResponse> DetectTextAdvancedAsync(DlpAdvancedDetectionRequest body = default(DlpAdvancedDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Detect User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpAdvancedDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpAdvancedDetectionResponse>> DetectTextAdvancedWithHttpInfoAsync(DlpAdvancedDetectionRequest body = default(DlpAdvancedDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDetectApi : IDetectApiSync, IDetectApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DetectApi : IDetectApi
    {
        private Cloudmersive.APIClient.NET.DLP.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DetectApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DetectApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DetectApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DetectApi(string basePath)
        {
            this.Configuration = Cloudmersive.APIClient.NET.DLP.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.DLP.Client.GlobalConfiguration.Instance,
                new Cloudmersive.APIClient.NET.DLP.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Cloudmersive.APIClient.NET.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DetectApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DetectApi(Cloudmersive.APIClient.NET.DLP.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Cloudmersive.APIClient.NET.DLP.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.DLP.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Cloudmersive.APIClient.NET.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DetectApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DetectApi(Cloudmersive.APIClient.NET.DLP.Client.ISynchronousClient client, Cloudmersive.APIClient.NET.DLP.Client.IAsynchronousClient asyncClient, Cloudmersive.APIClient.NET.DLP.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Cloudmersive.APIClient.NET.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Cloudmersive.APIClient.NET.DLP.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Cloudmersive.APIClient.NET.DLP.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NET.DLP.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NET.DLP.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Detect User Data in Document Image Detects configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpDetectionResponse</returns>
        public DlpDetectionResponse DetectDocument(DlpDocumentDetectionRequest body = default(DlpDocumentDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDetectionResponse> localVarResponse = DetectDocumentWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Document Image Detects configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpDetectionResponse</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDetectionResponse> DetectDocumentWithHttpInfo(DlpDocumentDetectionRequest body = default(DlpDocumentDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "DetectApi.DetectDocument";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpDetectionResponse>("/dlp/detect/document", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectDocument", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Detect User Data in Document Image Detects configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpDetectionResponse</returns>
        public async System.Threading.Tasks.Task<DlpDetectionResponse> DetectDocumentAsync(DlpDocumentDetectionRequest body = default(DlpDocumentDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDetectionResponse> localVarResponse = await DetectDocumentWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Document Image Detects configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDetectionResponse>> DetectDocumentWithHttpInfoAsync(DlpDocumentDetectionRequest body = default(DlpDocumentDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "DetectApi.DetectDocument";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpDetectionResponse>("/dlp/detect/document", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectDocument", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Detect User Data in Document Image (Advanced) Detects 29 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpAdvancedDetectionResponse</returns>
        public DlpAdvancedDetectionResponse DetectDocumentAdvanced(DlpAdvancedDocumentDetectionRequest body = default(DlpAdvancedDocumentDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDetectionResponse> localVarResponse = DetectDocumentAdvancedWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Document Image (Advanced) Detects 29 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpAdvancedDetectionResponse</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDetectionResponse> DetectDocumentAdvancedWithHttpInfo(DlpAdvancedDocumentDetectionRequest body = default(DlpAdvancedDocumentDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "DetectApi.DetectDocumentAdvanced";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpAdvancedDetectionResponse>("/dlp/detect/document/advanced", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectDocumentAdvanced", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Detect User Data in Document Image (Advanced) Detects 29 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpAdvancedDetectionResponse</returns>
        public async System.Threading.Tasks.Task<DlpAdvancedDetectionResponse> DetectDocumentAdvancedAsync(DlpAdvancedDocumentDetectionRequest body = default(DlpAdvancedDocumentDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDetectionResponse> localVarResponse = await DetectDocumentAdvancedWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Document Image (Advanced) Detects 29 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpAdvancedDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDetectionResponse>> DetectDocumentAdvancedWithHttpInfoAsync(DlpAdvancedDocumentDetectionRequest body = default(DlpAdvancedDocumentDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "DetectApi.DetectDocumentAdvanced";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpAdvancedDetectionResponse>("/dlp/detect/document/advanced", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectDocumentAdvanced", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Detect User Data in Input Text Detects configurable types of user data in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpDetectionResponse</returns>
        public DlpDetectionResponse DetectText(DlpDetectionRequest body = default(DlpDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDetectionResponse> localVarResponse = DetectTextWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Input Text Detects configurable types of user data in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpDetectionResponse</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDetectionResponse> DetectTextWithHttpInfo(DlpDetectionRequest body = default(DlpDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "DetectApi.DetectText";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpDetectionResponse>("/dlp/detect/text", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectText", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Detect User Data in Input Text Detects configurable types of user data in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpDetectionResponse</returns>
        public async System.Threading.Tasks.Task<DlpDetectionResponse> DetectTextAsync(DlpDetectionRequest body = default(DlpDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDetectionResponse> localVarResponse = await DetectTextWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Input Text Detects configurable types of user data in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDetectionResponse>> DetectTextWithHttpInfoAsync(DlpDetectionRequest body = default(DlpDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "DetectApi.DetectText";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpDetectionResponse>("/dlp/detect/text", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectText", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Detect User Data in Input Text (Advanced) Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpAdvancedDetectionResponse</returns>
        public DlpAdvancedDetectionResponse DetectTextAdvanced(DlpAdvancedDetectionRequest body = default(DlpAdvancedDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDetectionResponse> localVarResponse = DetectTextAdvancedWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Input Text (Advanced) Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpAdvancedDetectionResponse</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDetectionResponse> DetectTextAdvancedWithHttpInfo(DlpAdvancedDetectionRequest body = default(DlpAdvancedDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "DetectApi.DetectTextAdvanced";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpAdvancedDetectionResponse>("/dlp/detect/text/advanced", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectTextAdvanced", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Detect User Data in Input Text (Advanced) Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpAdvancedDetectionResponse</returns>
        public async System.Threading.Tasks.Task<DlpAdvancedDetectionResponse> DetectTextAdvancedAsync(DlpAdvancedDetectionRequest body = default(DlpAdvancedDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDetectionResponse> localVarResponse = await DetectTextAdvancedWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Input Text (Advanced) Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpAdvancedDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDetectionResponse>> DetectTextAdvancedWithHttpInfoAsync(DlpAdvancedDetectionRequest body = default(DlpAdvancedDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "DetectApi.DetectTextAdvanced";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpAdvancedDetectionResponse>("/dlp/detect/text/advanced", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectTextAdvanced", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
