/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Cloudmersive.APIClient.NET.DLP.Client;
using Cloudmersive.APIClient.NET.DLP.Model;

namespace Cloudmersive.APIClient.NET.DLP.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRedactApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Redact User Data in Document
        /// </summary>
        /// <remarks>
        /// Detects and redacts configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a grid-overlay approach, blurs those regions, and returns a rasterized PDF.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpDocumentRedactionResponse</returns>
        DlpDocumentRedactionResponse RedactDocument(DlpDocumentRedactionRequest body = default(DlpDocumentRedactionRequest), int operationIndex = 0);

        /// <summary>
        /// Redact User Data in Document
        /// </summary>
        /// <remarks>
        /// Detects and redacts configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a grid-overlay approach, blurs those regions, and returns a rasterized PDF.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpDocumentRedactionResponse</returns>
        ApiResponse<DlpDocumentRedactionResponse> RedactDocumentWithHttpInfo(DlpDocumentRedactionRequest body = default(DlpDocumentRedactionRequest), int operationIndex = 0);
        /// <summary>
        /// Redact User Data in Document (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects and redacts 35 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a row-overlay approach, redacts those regions, and returns a rasterized PDF.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpAdvancedDocumentRedactionResponse</returns>
        DlpAdvancedDocumentRedactionResponse RedactDocumentAdvanced(DlpAdvancedDocumentRedactionRequest body = default(DlpAdvancedDocumentRedactionRequest), int operationIndex = 0);

        /// <summary>
        /// Redact User Data in Document (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects and redacts 35 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a row-overlay approach, redacts those regions, and returns a rasterized PDF.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpAdvancedDocumentRedactionResponse</returns>
        ApiResponse<DlpAdvancedDocumentRedactionResponse> RedactDocumentAdvancedWithHttpInfo(DlpAdvancedDocumentRedactionRequest body = default(DlpAdvancedDocumentRedactionRequest), int operationIndex = 0);
        /// <summary>
        /// Redact User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects and redacts configurable types of user data in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpRedactionResponse</returns>
        DlpRedactionResponse RedactText(DlpRedactionRequest body = default(DlpRedactionRequest), int operationIndex = 0);

        /// <summary>
        /// Redact User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects and redacts configurable types of user data in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpRedactionResponse</returns>
        ApiResponse<DlpRedactionResponse> RedactTextWithHttpInfo(DlpRedactionRequest body = default(DlpRedactionRequest), int operationIndex = 0);
        /// <summary>
        /// Redact User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects and redacts 34 configurable types of user data including health-related PHI in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpAdvancedRedactionResponse</returns>
        DlpAdvancedRedactionResponse RedactTextAdvanced(DlpAdvancedRedactionRequest body = default(DlpAdvancedRedactionRequest), int operationIndex = 0);

        /// <summary>
        /// Redact User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects and redacts 34 configurable types of user data including health-related PHI in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpAdvancedRedactionResponse</returns>
        ApiResponse<DlpAdvancedRedactionResponse> RedactTextAdvancedWithHttpInfo(DlpAdvancedRedactionRequest body = default(DlpAdvancedRedactionRequest), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRedactApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Redact User Data in Document
        /// </summary>
        /// <remarks>
        /// Detects and redacts configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a grid-overlay approach, blurs those regions, and returns a rasterized PDF.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpDocumentRedactionResponse</returns>
        System.Threading.Tasks.Task<DlpDocumentRedactionResponse> RedactDocumentAsync(DlpDocumentRedactionRequest body = default(DlpDocumentRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Redact User Data in Document
        /// </summary>
        /// <remarks>
        /// Detects and redacts configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a grid-overlay approach, blurs those regions, and returns a rasterized PDF.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpDocumentRedactionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpDocumentRedactionResponse>> RedactDocumentWithHttpInfoAsync(DlpDocumentRedactionRequest body = default(DlpDocumentRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Redact User Data in Document (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects and redacts 35 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a row-overlay approach, redacts those regions, and returns a rasterized PDF.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpAdvancedDocumentRedactionResponse</returns>
        System.Threading.Tasks.Task<DlpAdvancedDocumentRedactionResponse> RedactDocumentAdvancedAsync(DlpAdvancedDocumentRedactionRequest body = default(DlpAdvancedDocumentRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Redact User Data in Document (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects and redacts 35 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a row-overlay approach, redacts those regions, and returns a rasterized PDF.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpAdvancedDocumentRedactionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpAdvancedDocumentRedactionResponse>> RedactDocumentAdvancedWithHttpInfoAsync(DlpAdvancedDocumentRedactionRequest body = default(DlpAdvancedDocumentRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Redact User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects and redacts configurable types of user data in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpRedactionResponse</returns>
        System.Threading.Tasks.Task<DlpRedactionResponse> RedactTextAsync(DlpRedactionRequest body = default(DlpRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Redact User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects and redacts configurable types of user data in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpRedactionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpRedactionResponse>> RedactTextWithHttpInfoAsync(DlpRedactionRequest body = default(DlpRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Redact User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects and redacts 34 configurable types of user data including health-related PHI in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpAdvancedRedactionResponse</returns>
        System.Threading.Tasks.Task<DlpAdvancedRedactionResponse> RedactTextAdvancedAsync(DlpAdvancedRedactionRequest body = default(DlpAdvancedRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Redact User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects and redacts 34 configurable types of user data including health-related PHI in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpAdvancedRedactionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpAdvancedRedactionResponse>> RedactTextAdvancedWithHttpInfoAsync(DlpAdvancedRedactionRequest body = default(DlpAdvancedRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRedactApi : IRedactApiSync, IRedactApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RedactApi : IRedactApi
    {
        private Cloudmersive.APIClient.NET.DLP.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RedactApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RedactApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RedactApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RedactApi(string basePath)
        {
            this.Configuration = Cloudmersive.APIClient.NET.DLP.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.DLP.Client.GlobalConfiguration.Instance,
                new Cloudmersive.APIClient.NET.DLP.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Cloudmersive.APIClient.NET.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RedactApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RedactApi(Cloudmersive.APIClient.NET.DLP.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Cloudmersive.APIClient.NET.DLP.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.DLP.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Cloudmersive.APIClient.NET.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RedactApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RedactApi(Cloudmersive.APIClient.NET.DLP.Client.ISynchronousClient client, Cloudmersive.APIClient.NET.DLP.Client.IAsynchronousClient asyncClient, Cloudmersive.APIClient.NET.DLP.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Cloudmersive.APIClient.NET.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Cloudmersive.APIClient.NET.DLP.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Cloudmersive.APIClient.NET.DLP.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NET.DLP.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NET.DLP.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Redact User Data in Document Detects and redacts configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a grid-overlay approach, blurs those regions, and returns a rasterized PDF.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpDocumentRedactionResponse</returns>
        public DlpDocumentRedactionResponse RedactDocument(DlpDocumentRedactionRequest body = default(DlpDocumentRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDocumentRedactionResponse> localVarResponse = RedactDocumentWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Document Detects and redacts configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a grid-overlay approach, blurs those regions, and returns a rasterized PDF.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpDocumentRedactionResponse</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDocumentRedactionResponse> RedactDocumentWithHttpInfo(DlpDocumentRedactionRequest body = default(DlpDocumentRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "RedactApi.RedactDocument";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpDocumentRedactionResponse>("/dlp/redact/document", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactDocument", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Redact User Data in Document Detects and redacts configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a grid-overlay approach, blurs those regions, and returns a rasterized PDF.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpDocumentRedactionResponse</returns>
        public async System.Threading.Tasks.Task<DlpDocumentRedactionResponse> RedactDocumentAsync(DlpDocumentRedactionRequest body = default(DlpDocumentRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDocumentRedactionResponse> localVarResponse = await RedactDocumentWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Document Detects and redacts configurable types of user data in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a grid-overlay approach, blurs those regions, and returns a rasterized PDF.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpDocumentRedactionResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpDocumentRedactionResponse>> RedactDocumentWithHttpInfoAsync(DlpDocumentRedactionRequest body = default(DlpDocumentRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "RedactApi.RedactDocument";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpDocumentRedactionResponse>("/dlp/redact/document", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactDocument", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Redact User Data in Document (Advanced) Detects and redacts 35 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a row-overlay approach, redacts those regions, and returns a rasterized PDF.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpAdvancedDocumentRedactionResponse</returns>
        public DlpAdvancedDocumentRedactionResponse RedactDocumentAdvanced(DlpAdvancedDocumentRedactionRequest body = default(DlpAdvancedDocumentRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDocumentRedactionResponse> localVarResponse = RedactDocumentAdvancedWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Document (Advanced) Detects and redacts 35 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a row-overlay approach, redacts those regions, and returns a rasterized PDF.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpAdvancedDocumentRedactionResponse</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDocumentRedactionResponse> RedactDocumentAdvancedWithHttpInfo(DlpAdvancedDocumentRedactionRequest body = default(DlpAdvancedDocumentRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "RedactApi.RedactDocumentAdvanced";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpAdvancedDocumentRedactionResponse>("/dlp/redact/document/advanced", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactDocumentAdvanced", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Redact User Data in Document (Advanced) Detects and redacts 35 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a row-overlay approach, redacts those regions, and returns a rasterized PDF.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpAdvancedDocumentRedactionResponse</returns>
        public async System.Threading.Tasks.Task<DlpAdvancedDocumentRedactionResponse> RedactDocumentAdvancedAsync(DlpAdvancedDocumentRedactionRequest body = default(DlpAdvancedDocumentRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDocumentRedactionResponse> localVarResponse = await RedactDocumentAdvancedWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Document (Advanced) Detects and redacts 35 configurable types of user data including health-related PHI in a document (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, HTML, EML, MSG, PNG, JPG, WEBP) using Advanced AI. Rasterizes document pages, detects PII regions using a row-overlay approach, redacts those regions, and returns a rasterized PDF.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpAdvancedDocumentRedactionResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedDocumentRedactionResponse>> RedactDocumentAdvancedWithHttpInfoAsync(DlpAdvancedDocumentRedactionRequest body = default(DlpAdvancedDocumentRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "RedactApi.RedactDocumentAdvanced";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpAdvancedDocumentRedactionResponse>("/dlp/redact/document/advanced", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactDocumentAdvanced", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Redact User Data in Input Text Detects and redacts configurable types of user data in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpRedactionResponse</returns>
        public DlpRedactionResponse RedactText(DlpRedactionRequest body = default(DlpRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpRedactionResponse> localVarResponse = RedactTextWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Input Text Detects and redacts configurable types of user data in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpRedactionResponse</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpRedactionResponse> RedactTextWithHttpInfo(DlpRedactionRequest body = default(DlpRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "RedactApi.RedactText";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpRedactionResponse>("/dlp/redact/text", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactText", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Redact User Data in Input Text Detects and redacts configurable types of user data in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpRedactionResponse</returns>
        public async System.Threading.Tasks.Task<DlpRedactionResponse> RedactTextAsync(DlpRedactionRequest body = default(DlpRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpRedactionResponse> localVarResponse = await RedactTextWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Input Text Detects and redacts configurable types of user data in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpRedactionResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpRedactionResponse>> RedactTextWithHttpInfoAsync(DlpRedactionRequest body = default(DlpRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "RedactApi.RedactText";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpRedactionResponse>("/dlp/redact/text", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactText", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Redact User Data in Input Text (Advanced) Detects and redacts 34 configurable types of user data including health-related PHI in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpAdvancedRedactionResponse</returns>
        public DlpAdvancedRedactionResponse RedactTextAdvanced(DlpAdvancedRedactionRequest body = default(DlpAdvancedRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedRedactionResponse> localVarResponse = RedactTextAdvancedWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Input Text (Advanced) Detects and redacts 34 configurable types of user data including health-related PHI in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpAdvancedRedactionResponse</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedRedactionResponse> RedactTextAdvancedWithHttpInfo(DlpAdvancedRedactionRequest body = default(DlpAdvancedRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "RedactApi.RedactTextAdvanced";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpAdvancedRedactionResponse>("/dlp/redact/text/advanced", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactTextAdvanced", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Redact User Data in Input Text (Advanced) Detects and redacts 34 configurable types of user data including health-related PHI in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpAdvancedRedactionResponse</returns>
        public async System.Threading.Tasks.Task<DlpAdvancedRedactionResponse> RedactTextAdvancedAsync(DlpAdvancedRedactionRequest body = default(DlpAdvancedRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedRedactionResponse> localVarResponse = await RedactTextAdvancedWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Input Text (Advanced) Detects and redacts 34 configurable types of user data including health-related PHI in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpAdvancedRedactionResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpAdvancedRedactionResponse>> RedactTextAdvancedWithHttpInfoAsync(DlpAdvancedRedactionRequest body = default(DlpAdvancedRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "RedactApi.RedactTextAdvanced";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpAdvancedRedactionResponse>("/dlp/redact/text/advanced", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactTextAdvanced", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
