/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Cloudmersive.APIClient.NET.DLP.Client;
using Cloudmersive.APIClient.NET.DLP.Model;

namespace Cloudmersive.APIClient.NET.DLP.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITasksBatchJobApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpBatchJobResult</returns>
        DlpBatchJobResult DetectAudioAdvancedBatchJob(DlpAdvancedAudioDetectionRequest body = default(DlpAdvancedAudioDetectionRequest), int operationIndex = 0);

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        ApiResponse<DlpBatchJobResult> DetectAudioAdvancedBatchJobWithHttpInfo(DlpAdvancedAudioDetectionRequest body = default(DlpAdvancedAudioDetectionRequest), int operationIndex = 0);
        /// <summary>
        /// Detect User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpBatchJobResult</returns>
        DlpBatchJobResult DetectAudioBatchJob(DlpAudioDetectionRequest body = default(DlpAudioDetectionRequest), int operationIndex = 0);

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        ApiResponse<DlpBatchJobResult> DetectAudioBatchJobWithHttpInfo(DlpAudioDetectionRequest body = default(DlpAudioDetectionRequest), int operationIndex = 0);
        /// <summary>
        /// Get the status and result of a DLP Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpBatchJobStatusResult</returns>
        DlpBatchJobStatusResult GetAsyncJobStatus(string asyncJobID = default(string), int operationIndex = 0);

        /// <summary>
        /// Get the status and result of a DLP Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpBatchJobStatusResult</returns>
        ApiResponse<DlpBatchJobStatusResult> GetAsyncJobStatusWithHttpInfo(string asyncJobID = default(string), int operationIndex = 0);
        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpBatchJobResult</returns>
        DlpBatchJobResult RedactAudioAdvancedBatchJob(DlpAdvancedAudioRedactionRequest body = default(DlpAdvancedAudioRedactionRequest), int operationIndex = 0);

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        ApiResponse<DlpBatchJobResult> RedactAudioAdvancedBatchJobWithHttpInfo(DlpAdvancedAudioRedactionRequest body = default(DlpAdvancedAudioRedactionRequest), int operationIndex = 0);
        /// <summary>
        /// Redact User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpBatchJobResult</returns>
        DlpBatchJobResult RedactAudioBatchJob(DlpAudioRedactionRequest body = default(DlpAudioRedactionRequest), int operationIndex = 0);

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        ApiResponse<DlpBatchJobResult> RedactAudioBatchJobWithHttpInfo(DlpAudioRedactionRequest body = default(DlpAudioRedactionRequest), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITasksBatchJobApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        System.Threading.Tasks.Task<DlpBatchJobResult> DetectAudioAdvancedBatchJobAsync(DlpAdvancedAudioDetectionRequest body = default(DlpAdvancedAudioDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> DetectAudioAdvancedBatchJobWithHttpInfoAsync(DlpAdvancedAudioDetectionRequest body = default(DlpAdvancedAudioDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Detect User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        System.Threading.Tasks.Task<DlpBatchJobResult> DetectAudioBatchJobAsync(DlpAudioDetectionRequest body = default(DlpAudioDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> DetectAudioBatchJobWithHttpInfoAsync(DlpAudioDetectionRequest body = default(DlpAudioDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get the status and result of a DLP Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpBatchJobStatusResult</returns>
        System.Threading.Tasks.Task<DlpBatchJobStatusResult> GetAsyncJobStatusAsync(string asyncJobID = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get the status and result of a DLP Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpBatchJobStatusResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpBatchJobStatusResult>> GetAsyncJobStatusWithHttpInfoAsync(string asyncJobID = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        System.Threading.Tasks.Task<DlpBatchJobResult> RedactAudioAdvancedBatchJobAsync(DlpAdvancedAudioRedactionRequest body = default(DlpAdvancedAudioRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> RedactAudioAdvancedBatchJobWithHttpInfoAsync(DlpAdvancedAudioRedactionRequest body = default(DlpAdvancedAudioRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Redact User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        System.Threading.Tasks.Task<DlpBatchJobResult> RedactAudioBatchJobAsync(DlpAudioRedactionRequest body = default(DlpAudioRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> RedactAudioBatchJobWithHttpInfoAsync(DlpAudioRedactionRequest body = default(DlpAudioRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITasksBatchJobApi : ITasksBatchJobApiSync, ITasksBatchJobApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TasksBatchJobApi : ITasksBatchJobApi
    {
        private Cloudmersive.APIClient.NET.DLP.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TasksBatchJobApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TasksBatchJobApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TasksBatchJobApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TasksBatchJobApi(string basePath)
        {
            this.Configuration = Cloudmersive.APIClient.NET.DLP.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.DLP.Client.GlobalConfiguration.Instance,
                new Cloudmersive.APIClient.NET.DLP.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Cloudmersive.APIClient.NET.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TasksBatchJobApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TasksBatchJobApi(Cloudmersive.APIClient.NET.DLP.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Cloudmersive.APIClient.NET.DLP.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.DLP.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Cloudmersive.APIClient.NET.DLP.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Cloudmersive.APIClient.NET.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TasksBatchJobApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public TasksBatchJobApi(Cloudmersive.APIClient.NET.DLP.Client.ISynchronousClient client, Cloudmersive.APIClient.NET.DLP.Client.IAsynchronousClient asyncClient, Cloudmersive.APIClient.NET.DLP.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Cloudmersive.APIClient.NET.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Cloudmersive.APIClient.NET.DLP.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Cloudmersive.APIClient.NET.DLP.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NET.DLP.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NET.DLP.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpBatchJobResult</returns>
        public DlpBatchJobResult DetectAudioAdvancedBatchJob(DlpAdvancedAudioDetectionRequest body = default(DlpAdvancedAudioDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> localVarResponse = DetectAudioAdvancedBatchJobWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> DetectAudioAdvancedBatchJobWithHttpInfo(DlpAdvancedAudioDetectionRequest body = default(DlpAdvancedAudioDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "TasksBatchJobApi.DetectAudioAdvancedBatchJob";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpBatchJobResult>("/dlp/batch-job/detect/audio/advanced", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectAudioAdvancedBatchJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        public async System.Threading.Tasks.Task<DlpBatchJobResult> DetectAudioAdvancedBatchJobAsync(DlpAdvancedAudioDetectionRequest body = default(DlpAdvancedAudioDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> localVarResponse = await DetectAudioAdvancedBatchJobWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult>> DetectAudioAdvancedBatchJobWithHttpInfoAsync(DlpAdvancedAudioDetectionRequest body = default(DlpAdvancedAudioDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "TasksBatchJobApi.DetectAudioAdvancedBatchJob";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpBatchJobResult>("/dlp/batch-job/detect/audio/advanced", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectAudioAdvancedBatchJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpBatchJobResult</returns>
        public DlpBatchJobResult DetectAudioBatchJob(DlpAudioDetectionRequest body = default(DlpAudioDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> localVarResponse = DetectAudioBatchJobWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> DetectAudioBatchJobWithHttpInfo(DlpAudioDetectionRequest body = default(DlpAudioDetectionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "TasksBatchJobApi.DetectAudioBatchJob";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpBatchJobResult>("/dlp/batch-job/detect/audio", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectAudioBatchJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        public async System.Threading.Tasks.Task<DlpBatchJobResult> DetectAudioBatchJobAsync(DlpAudioDetectionRequest body = default(DlpAudioDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> localVarResponse = await DetectAudioBatchJobWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult>> DetectAudioBatchJobWithHttpInfoAsync(DlpAudioDetectionRequest body = default(DlpAudioDetectionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "TasksBatchJobApi.DetectAudioBatchJob";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpBatchJobResult>("/dlp/batch-job/detect/audio", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DetectAudioBatchJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get the status and result of a DLP Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpBatchJobStatusResult</returns>
        public DlpBatchJobStatusResult GetAsyncJobStatus(string asyncJobID = default(string), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobStatusResult> localVarResponse = GetAsyncJobStatusWithHttpInfo(asyncJobID);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get the status and result of a DLP Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpBatchJobStatusResult</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobStatusResult> GetAsyncJobStatusWithHttpInfo(string asyncJobID = default(string), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (asyncJobID != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.ParameterToMultiMap("", "AsyncJobID", asyncJobID));
            }

            localVarRequestOptions.Operation = "TasksBatchJobApi.GetAsyncJobStatus";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DlpBatchJobStatusResult>("/dlp/batch-job/status", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAsyncJobStatus", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get the status and result of a DLP Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpBatchJobStatusResult</returns>
        public async System.Threading.Tasks.Task<DlpBatchJobStatusResult> GetAsyncJobStatusAsync(string asyncJobID = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobStatusResult> localVarResponse = await GetAsyncJobStatusWithHttpInfoAsync(asyncJobID, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get the status and result of a DLP Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpBatchJobStatusResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobStatusResult>> GetAsyncJobStatusWithHttpInfoAsync(string asyncJobID = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (asyncJobID != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.ParameterToMultiMap("", "AsyncJobID", asyncJobID));
            }

            localVarRequestOptions.Operation = "TasksBatchJobApi.GetAsyncJobStatus";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<DlpBatchJobStatusResult>("/dlp/batch-job/status", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAsyncJobStatus", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpBatchJobResult</returns>
        public DlpBatchJobResult RedactAudioAdvancedBatchJob(DlpAdvancedAudioRedactionRequest body = default(DlpAdvancedAudioRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> localVarResponse = RedactAudioAdvancedBatchJobWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> RedactAudioAdvancedBatchJobWithHttpInfo(DlpAdvancedAudioRedactionRequest body = default(DlpAdvancedAudioRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "TasksBatchJobApi.RedactAudioAdvancedBatchJob";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpBatchJobResult>("/dlp/batch-job/redact/audio/advanced", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactAudioAdvancedBatchJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        public async System.Threading.Tasks.Task<DlpBatchJobResult> RedactAudioAdvancedBatchJobAsync(DlpAdvancedAudioRedactionRequest body = default(DlpAdvancedAudioRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> localVarResponse = await RedactAudioAdvancedBatchJobWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult>> RedactAudioAdvancedBatchJobWithHttpInfoAsync(DlpAdvancedAudioRedactionRequest body = default(DlpAdvancedAudioRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "TasksBatchJobApi.RedactAudioAdvancedBatchJob";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpBatchJobResult>("/dlp/batch-job/redact/audio/advanced", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactAudioAdvancedBatchJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DlpBatchJobResult</returns>
        public DlpBatchJobResult RedactAudioBatchJob(DlpAudioRedactionRequest body = default(DlpAudioRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> localVarResponse = RedactAudioBatchJobWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        public Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> RedactAudioBatchJobWithHttpInfo(DlpAudioRedactionRequest body = default(DlpAudioRedactionRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "TasksBatchJobApi.RedactAudioBatchJob";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DlpBatchJobResult>("/dlp/batch-job/redact/audio", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactAudioBatchJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        public async System.Threading.Tasks.Task<DlpBatchJobResult> RedactAudioBatchJobAsync(DlpAudioRedactionRequest body = default(DlpAudioRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult> localVarResponse = await RedactAudioBatchJobWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.DLP.Client.ApiResponse<DlpBatchJobResult>> RedactAudioBatchJobWithHttpInfoAsync(DlpAudioRedactionRequest body = default(DlpAudioRedactionRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.DLP.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.DLP.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NET.DLP.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "TasksBatchJobApi.RedactAudioBatchJob";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DlpBatchJobResult>("/dlp/batch-job/redact/audio", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RedactAudioBatchJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
