/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DLP.Model;
using Cloudmersive.APIClient.NET.DLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DLP.Test.Model
{
    /// <summary>
    ///  Class for testing AudioTimestamp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AudioTimestampTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AudioTimestamp
        //private AudioTimestamp instance;

        public AudioTimestampTests()
        {
            // TODO uncomment below to create an instance of AudioTimestamp
            //instance = new AudioTimestamp();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AudioTimestamp
        /// </summary>
        [Fact]
        public void AudioTimestampInstanceTest()
        {
            // TODO uncomment below to test "IsType" AudioTimestamp
            //Assert.IsType<AudioTimestamp>(instance);
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

        /// <summary>
        /// Test the property 'CharacterOffsetStart'
        /// </summary>
        [Fact]
        public void CharacterOffsetStartTest()
        {
            // TODO unit test for the property 'CharacterOffsetStart'
        }

        /// <summary>
        /// Test the property 'CharacterOffsetEnd'
        /// </summary>
        [Fact]
        public void CharacterOffsetEndTest()
        {
            // TODO unit test for the property 'CharacterOffsetEnd'
        }

        /// <summary>
        /// Test the property 'StartTimeMs'
        /// </summary>
        [Fact]
        public void StartTimeMsTest()
        {
            // TODO unit test for the property 'StartTimeMs'
        }

        /// <summary>
        /// Test the property 'EndTimeMs'
        /// </summary>
        [Fact]
        public void EndTimeMsTest()
        {
            // TODO unit test for the property 'EndTimeMs'
        }
    }
}
