/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DLP.Model;
using Cloudmersive.APIClient.NET.DLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DLP.Test.Model
{
    /// <summary>
    ///  Class for testing DlpAdvancedDetectionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DlpAdvancedDetectionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DlpAdvancedDetectionResponse
        //private DlpAdvancedDetectionResponse instance;

        public DlpAdvancedDetectionResponseTests()
        {
            // TODO uncomment below to create an instance of DlpAdvancedDetectionResponse
            //instance = new DlpAdvancedDetectionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DlpAdvancedDetectionResponse
        /// </summary>
        [Fact]
        public void DlpAdvancedDetectionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DlpAdvancedDetectionResponse
            //Assert.IsType<DlpAdvancedDetectionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'ContainsEmailAddress'
        /// </summary>
        [Fact]
        public void ContainsEmailAddressTest()
        {
            // TODO unit test for the property 'ContainsEmailAddress'
        }

        /// <summary>
        /// Test the property 'ContainsPhoneNumber'
        /// </summary>
        [Fact]
        public void ContainsPhoneNumberTest()
        {
            // TODO unit test for the property 'ContainsPhoneNumber'
        }

        /// <summary>
        /// Test the property 'ContainsStreetAddress'
        /// </summary>
        [Fact]
        public void ContainsStreetAddressTest()
        {
            // TODO unit test for the property 'ContainsStreetAddress'
        }

        /// <summary>
        /// Test the property 'ContainsPersonName'
        /// </summary>
        [Fact]
        public void ContainsPersonNameTest()
        {
            // TODO unit test for the property 'ContainsPersonName'
        }

        /// <summary>
        /// Test the property 'ContainsBirthDate'
        /// </summary>
        [Fact]
        public void ContainsBirthDateTest()
        {
            // TODO unit test for the property 'ContainsBirthDate'
        }

        /// <summary>
        /// Test the property 'ContainsPassportNumber'
        /// </summary>
        [Fact]
        public void ContainsPassportNumberTest()
        {
            // TODO unit test for the property 'ContainsPassportNumber'
        }

        /// <summary>
        /// Test the property 'ContainsDriversLicense'
        /// </summary>
        [Fact]
        public void ContainsDriversLicenseTest()
        {
            // TODO unit test for the property 'ContainsDriversLicense'
        }

        /// <summary>
        /// Test the property 'ContainsSocialSecurityNumber'
        /// </summary>
        [Fact]
        public void ContainsSocialSecurityNumberTest()
        {
            // TODO unit test for the property 'ContainsSocialSecurityNumber'
        }

        /// <summary>
        /// Test the property 'ContainsTaxpayerID'
        /// </summary>
        [Fact]
        public void ContainsTaxpayerIDTest()
        {
            // TODO unit test for the property 'ContainsTaxpayerID'
        }

        /// <summary>
        /// Test the property 'ContainsCreditCardNumber'
        /// </summary>
        [Fact]
        public void ContainsCreditCardNumberTest()
        {
            // TODO unit test for the property 'ContainsCreditCardNumber'
        }

        /// <summary>
        /// Test the property 'ContainsCreditCardExpirationDate'
        /// </summary>
        [Fact]
        public void ContainsCreditCardExpirationDateTest()
        {
            // TODO unit test for the property 'ContainsCreditCardExpirationDate'
        }

        /// <summary>
        /// Test the property 'ContainsCreditCardVerificationCode'
        /// </summary>
        [Fact]
        public void ContainsCreditCardVerificationCodeTest()
        {
            // TODO unit test for the property 'ContainsCreditCardVerificationCode'
        }

        /// <summary>
        /// Test the property 'ContainsBankAccountNumber'
        /// </summary>
        [Fact]
        public void ContainsBankAccountNumberTest()
        {
            // TODO unit test for the property 'ContainsBankAccountNumber'
        }

        /// <summary>
        /// Test the property 'ContainsIBAN'
        /// </summary>
        [Fact]
        public void ContainsIBANTest()
        {
            // TODO unit test for the property 'ContainsIBAN'
        }

        /// <summary>
        /// Test the property 'ContainsHealthInsuranceNumber'
        /// </summary>
        [Fact]
        public void ContainsHealthInsuranceNumberTest()
        {
            // TODO unit test for the property 'ContainsHealthInsuranceNumber'
        }

        /// <summary>
        /// Test the property 'ContainsBearerToken'
        /// </summary>
        [Fact]
        public void ContainsBearerTokenTest()
        {
            // TODO unit test for the property 'ContainsBearerToken'
        }

        /// <summary>
        /// Test the property 'ContainsHttpCookie'
        /// </summary>
        [Fact]
        public void ContainsHttpCookieTest()
        {
            // TODO unit test for the property 'ContainsHttpCookie'
        }

        /// <summary>
        /// Test the property 'ContainsPrivateKeys'
        /// </summary>
        [Fact]
        public void ContainsPrivateKeysTest()
        {
            // TODO unit test for the property 'ContainsPrivateKeys'
        }

        /// <summary>
        /// Test the property 'ContainsCredentials'
        /// </summary>
        [Fact]
        public void ContainsCredentialsTest()
        {
            // TODO unit test for the property 'ContainsCredentials'
        }

        /// <summary>
        /// Test the property 'ContainsDeepWebUrls'
        /// </summary>
        [Fact]
        public void ContainsDeepWebUrlsTest()
        {
            // TODO unit test for the property 'ContainsDeepWebUrls'
        }

        /// <summary>
        /// Test the property 'ContainsSourceCode'
        /// </summary>
        [Fact]
        public void ContainsSourceCodeTest()
        {
            // TODO unit test for the property 'ContainsSourceCode'
        }

        /// <summary>
        /// Test the property 'ContainsIpAddress'
        /// </summary>
        [Fact]
        public void ContainsIpAddressTest()
        {
            // TODO unit test for the property 'ContainsIpAddress'
        }

        /// <summary>
        /// Test the property 'ContainsMacAddress'
        /// </summary>
        [Fact]
        public void ContainsMacAddressTest()
        {
            // TODO unit test for the property 'ContainsMacAddress'
        }

        /// <summary>
        /// Test the property 'ContainsHealthInsuranceMemberID'
        /// </summary>
        [Fact]
        public void ContainsHealthInsuranceMemberIDTest()
        {
            // TODO unit test for the property 'ContainsHealthInsuranceMemberID'
        }

        /// <summary>
        /// Test the property 'ContainsHealthInjuryOrDisease'
        /// </summary>
        [Fact]
        public void ContainsHealthInjuryOrDiseaseTest()
        {
            // TODO unit test for the property 'ContainsHealthInjuryOrDisease'
        }

        /// <summary>
        /// Test the property 'ContainsHealthTypeOfTreatment'
        /// </summary>
        [Fact]
        public void ContainsHealthTypeOfTreatmentTest()
        {
            // TODO unit test for the property 'ContainsHealthTypeOfTreatment'
        }

        /// <summary>
        /// Test the property 'ContainsHealthDateAndTimeOfTreatment'
        /// </summary>
        [Fact]
        public void ContainsHealthDateAndTimeOfTreatmentTest()
        {
            // TODO unit test for the property 'ContainsHealthDateAndTimeOfTreatment'
        }

        /// <summary>
        /// Test the property 'ContainsHealthPlanBeneficiaryNumber'
        /// </summary>
        [Fact]
        public void ContainsHealthPlanBeneficiaryNumberTest()
        {
            // TODO unit test for the property 'ContainsHealthPlanBeneficiaryNumber'
        }

        /// <summary>
        /// Test the property 'ContainsHealthPaymentsMadeForTreatment'
        /// </summary>
        [Fact]
        public void ContainsHealthPaymentsMadeForTreatmentTest()
        {
            // TODO unit test for the property 'ContainsHealthPaymentsMadeForTreatment'
        }

        /// <summary>
        /// Test the property 'ContainsFaces'
        /// </summary>
        [Fact]
        public void ContainsFacesTest()
        {
            // TODO unit test for the property 'ContainsFaces'
        }

        /// <summary>
        /// Test the property 'ContainsVehicleID'
        /// </summary>
        [Fact]
        public void ContainsVehicleIDTest()
        {
            // TODO unit test for the property 'ContainsVehicleID'
        }

        /// <summary>
        /// Test the property 'ContainsDeviceID'
        /// </summary>
        [Fact]
        public void ContainsDeviceIDTest()
        {
            // TODO unit test for the property 'ContainsDeviceID'
        }

        /// <summary>
        /// Test the property 'ContainsNamesOfRelatives'
        /// </summary>
        [Fact]
        public void ContainsNamesOfRelativesTest()
        {
            // TODO unit test for the property 'ContainsNamesOfRelatives'
        }

        /// <summary>
        /// Test the property 'ContainsHealthUniversalRecordLocator'
        /// </summary>
        [Fact]
        public void ContainsHealthUniversalRecordLocatorTest()
        {
            // TODO unit test for the property 'ContainsHealthUniversalRecordLocator'
        }

        /// <summary>
        /// Test the property 'ContainsBiometrics'
        /// </summary>
        [Fact]
        public void ContainsBiometricsTest()
        {
            // TODO unit test for the property 'ContainsBiometrics'
        }

        /// <summary>
        /// Test the property 'AnalysisRationale'
        /// </summary>
        [Fact]
        public void AnalysisRationaleTest()
        {
            // TODO unit test for the property 'AnalysisRationale'
        }
    }
}
