/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DLP.Model;
using Cloudmersive.APIClient.NET.DLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DLP.Test.Model
{
    /// <summary>
    ///  Class for testing DlpAdvancedDetectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DlpAdvancedDetectionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DlpAdvancedDetectionRequest
        //private DlpAdvancedDetectionRequest instance;

        public DlpAdvancedDetectionRequestTests()
        {
            // TODO uncomment below to create an instance of DlpAdvancedDetectionRequest
            //instance = new DlpAdvancedDetectionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DlpAdvancedDetectionRequest
        /// </summary>
        [Fact]
        public void DlpAdvancedDetectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DlpAdvancedDetectionRequest
            //Assert.IsType<DlpAdvancedDetectionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InputText'
        /// </summary>
        [Fact]
        public void InputTextTest()
        {
            // TODO unit test for the property 'InputText'
        }

        /// <summary>
        /// Test the property 'AllowEmailAddress'
        /// </summary>
        [Fact]
        public void AllowEmailAddressTest()
        {
            // TODO unit test for the property 'AllowEmailAddress'
        }

        /// <summary>
        /// Test the property 'AllowPhoneNumber'
        /// </summary>
        [Fact]
        public void AllowPhoneNumberTest()
        {
            // TODO unit test for the property 'AllowPhoneNumber'
        }

        /// <summary>
        /// Test the property 'AllowStreetAddress'
        /// </summary>
        [Fact]
        public void AllowStreetAddressTest()
        {
            // TODO unit test for the property 'AllowStreetAddress'
        }

        /// <summary>
        /// Test the property 'AllowPersonName'
        /// </summary>
        [Fact]
        public void AllowPersonNameTest()
        {
            // TODO unit test for the property 'AllowPersonName'
        }

        /// <summary>
        /// Test the property 'AllowBirthDate'
        /// </summary>
        [Fact]
        public void AllowBirthDateTest()
        {
            // TODO unit test for the property 'AllowBirthDate'
        }

        /// <summary>
        /// Test the property 'AllowPassportNumber'
        /// </summary>
        [Fact]
        public void AllowPassportNumberTest()
        {
            // TODO unit test for the property 'AllowPassportNumber'
        }

        /// <summary>
        /// Test the property 'AllowDriversLicense'
        /// </summary>
        [Fact]
        public void AllowDriversLicenseTest()
        {
            // TODO unit test for the property 'AllowDriversLicense'
        }

        /// <summary>
        /// Test the property 'AllowSocialSecurityNumber'
        /// </summary>
        [Fact]
        public void AllowSocialSecurityNumberTest()
        {
            // TODO unit test for the property 'AllowSocialSecurityNumber'
        }

        /// <summary>
        /// Test the property 'AllowTaxpayerID'
        /// </summary>
        [Fact]
        public void AllowTaxpayerIDTest()
        {
            // TODO unit test for the property 'AllowTaxpayerID'
        }

        /// <summary>
        /// Test the property 'AllowCreditCardNumber'
        /// </summary>
        [Fact]
        public void AllowCreditCardNumberTest()
        {
            // TODO unit test for the property 'AllowCreditCardNumber'
        }

        /// <summary>
        /// Test the property 'AllowCreditCardExpirationDate'
        /// </summary>
        [Fact]
        public void AllowCreditCardExpirationDateTest()
        {
            // TODO unit test for the property 'AllowCreditCardExpirationDate'
        }

        /// <summary>
        /// Test the property 'AllowCreditCardVerificationCode'
        /// </summary>
        [Fact]
        public void AllowCreditCardVerificationCodeTest()
        {
            // TODO unit test for the property 'AllowCreditCardVerificationCode'
        }

        /// <summary>
        /// Test the property 'AllowBankAccountNumber'
        /// </summary>
        [Fact]
        public void AllowBankAccountNumberTest()
        {
            // TODO unit test for the property 'AllowBankAccountNumber'
        }

        /// <summary>
        /// Test the property 'AllowIBAN'
        /// </summary>
        [Fact]
        public void AllowIBANTest()
        {
            // TODO unit test for the property 'AllowIBAN'
        }

        /// <summary>
        /// Test the property 'AllowHealthInsuranceNumber'
        /// </summary>
        [Fact]
        public void AllowHealthInsuranceNumberTest()
        {
            // TODO unit test for the property 'AllowHealthInsuranceNumber'
        }

        /// <summary>
        /// Test the property 'AllowBearerToken'
        /// </summary>
        [Fact]
        public void AllowBearerTokenTest()
        {
            // TODO unit test for the property 'AllowBearerToken'
        }

        /// <summary>
        /// Test the property 'AllowHttpCookie'
        /// </summary>
        [Fact]
        public void AllowHttpCookieTest()
        {
            // TODO unit test for the property 'AllowHttpCookie'
        }

        /// <summary>
        /// Test the property 'AllowPrivateKeys'
        /// </summary>
        [Fact]
        public void AllowPrivateKeysTest()
        {
            // TODO unit test for the property 'AllowPrivateKeys'
        }

        /// <summary>
        /// Test the property 'AllowCredentials'
        /// </summary>
        [Fact]
        public void AllowCredentialsTest()
        {
            // TODO unit test for the property 'AllowCredentials'
        }

        /// <summary>
        /// Test the property 'AllowDeepWebUrls'
        /// </summary>
        [Fact]
        public void AllowDeepWebUrlsTest()
        {
            // TODO unit test for the property 'AllowDeepWebUrls'
        }

        /// <summary>
        /// Test the property 'AllowSourceCode'
        /// </summary>
        [Fact]
        public void AllowSourceCodeTest()
        {
            // TODO unit test for the property 'AllowSourceCode'
        }

        /// <summary>
        /// Test the property 'AllowIpAddress'
        /// </summary>
        [Fact]
        public void AllowIpAddressTest()
        {
            // TODO unit test for the property 'AllowIpAddress'
        }

        /// <summary>
        /// Test the property 'AllowMacAddress'
        /// </summary>
        [Fact]
        public void AllowMacAddressTest()
        {
            // TODO unit test for the property 'AllowMacAddress'
        }

        /// <summary>
        /// Test the property 'AllowHealthInsuranceMemberID'
        /// </summary>
        [Fact]
        public void AllowHealthInsuranceMemberIDTest()
        {
            // TODO unit test for the property 'AllowHealthInsuranceMemberID'
        }

        /// <summary>
        /// Test the property 'AllowHealthInjuryOrDisease'
        /// </summary>
        [Fact]
        public void AllowHealthInjuryOrDiseaseTest()
        {
            // TODO unit test for the property 'AllowHealthInjuryOrDisease'
        }

        /// <summary>
        /// Test the property 'AllowHealthTypeOfTreatment'
        /// </summary>
        [Fact]
        public void AllowHealthTypeOfTreatmentTest()
        {
            // TODO unit test for the property 'AllowHealthTypeOfTreatment'
        }

        /// <summary>
        /// Test the property 'AllowHealthDateAndTimeOfTreatment'
        /// </summary>
        [Fact]
        public void AllowHealthDateAndTimeOfTreatmentTest()
        {
            // TODO unit test for the property 'AllowHealthDateAndTimeOfTreatment'
        }

        /// <summary>
        /// Test the property 'AllowHealthPlanBeneficiaryNumber'
        /// </summary>
        [Fact]
        public void AllowHealthPlanBeneficiaryNumberTest()
        {
            // TODO unit test for the property 'AllowHealthPlanBeneficiaryNumber'
        }

        /// <summary>
        /// Test the property 'AllowHealthPaymentsMadeForTreatment'
        /// </summary>
        [Fact]
        public void AllowHealthPaymentsMadeForTreatmentTest()
        {
            // TODO unit test for the property 'AllowHealthPaymentsMadeForTreatment'
        }

        /// <summary>
        /// Test the property 'AllowVehicleID'
        /// </summary>
        [Fact]
        public void AllowVehicleIDTest()
        {
            // TODO unit test for the property 'AllowVehicleID'
        }

        /// <summary>
        /// Test the property 'AllowDeviceID'
        /// </summary>
        [Fact]
        public void AllowDeviceIDTest()
        {
            // TODO unit test for the property 'AllowDeviceID'
        }

        /// <summary>
        /// Test the property 'AllowNamesOfRelatives'
        /// </summary>
        [Fact]
        public void AllowNamesOfRelativesTest()
        {
            // TODO unit test for the property 'AllowNamesOfRelatives'
        }

        /// <summary>
        /// Test the property 'AllowHealthUniversalRecordLocator'
        /// </summary>
        [Fact]
        public void AllowHealthUniversalRecordLocatorTest()
        {
            // TODO unit test for the property 'AllowHealthUniversalRecordLocator'
        }

        /// <summary>
        /// Test the property 'AllowBiometrics'
        /// </summary>
        [Fact]
        public void AllowBiometricsTest()
        {
            // TODO unit test for the property 'AllowBiometrics'
        }

        /// <summary>
        /// Test the property 'ProvideAnalysisRationale'
        /// </summary>
        [Fact]
        public void ProvideAnalysisRationaleTest()
        {
            // TODO unit test for the property 'ProvideAnalysisRationale'
        }

        /// <summary>
        /// Test the property 'CustomPolicyID'
        /// </summary>
        [Fact]
        public void CustomPolicyIDTest()
        {
            // TODO unit test for the property 'CustomPolicyID'
        }
    }
}
