/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DLP.Model;
using Cloudmersive.APIClient.NET.DLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DLP.Test.Model
{
    /// <summary>
    ///  Class for testing DlpBatchJobStatusResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DlpBatchJobStatusResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DlpBatchJobStatusResult
        //private DlpBatchJobStatusResult instance;

        public DlpBatchJobStatusResultTests()
        {
            // TODO uncomment below to create an instance of DlpBatchJobStatusResult
            //instance = new DlpBatchJobStatusResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DlpBatchJobStatusResult
        /// </summary>
        [Fact]
        public void DlpBatchJobStatusResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" DlpBatchJobStatusResult
            //Assert.IsType<DlpBatchJobStatusResult>(instance);
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'AsyncJobStatus'
        /// </summary>
        [Fact]
        public void AsyncJobStatusTest()
        {
            // TODO unit test for the property 'AsyncJobStatus'
        }

        /// <summary>
        /// Test the property 'AsyncJobID'
        /// </summary>
        [Fact]
        public void AsyncJobIDTest()
        {
            // TODO unit test for the property 'AsyncJobID'
        }

        /// <summary>
        /// Test the property 'DetectAudioResult'
        /// </summary>
        [Fact]
        public void DetectAudioResultTest()
        {
            // TODO unit test for the property 'DetectAudioResult'
        }

        /// <summary>
        /// Test the property 'DetectAudioAdvancedResult'
        /// </summary>
        [Fact]
        public void DetectAudioAdvancedResultTest()
        {
            // TODO unit test for the property 'DetectAudioAdvancedResult'
        }

        /// <summary>
        /// Test the property 'RedactAudioResult'
        /// </summary>
        [Fact]
        public void RedactAudioResultTest()
        {
            // TODO unit test for the property 'RedactAudioResult'
        }

        /// <summary>
        /// Test the property 'RedactAudioAdvancedResult'
        /// </summary>
        [Fact]
        public void RedactAudioAdvancedResultTest()
        {
            // TODO unit test for the property 'RedactAudioAdvancedResult'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
    }
}
