/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DLP.Model;
using Cloudmersive.APIClient.NET.DLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DLP.Test.Model
{
    /// <summary>
    ///  Class for testing DlpBatchJobResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DlpBatchJobResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DlpBatchJobResult
        //private DlpBatchJobResult instance;

        public DlpBatchJobResultTests()
        {
            // TODO uncomment below to create an instance of DlpBatchJobResult
            //instance = new DlpBatchJobResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DlpBatchJobResult
        /// </summary>
        [Fact]
        public void DlpBatchJobResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" DlpBatchJobResult
            //Assert.IsType<DlpBatchJobResult>(instance);
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'AsyncJobID'
        /// </summary>
        [Fact]
        public void AsyncJobIDTest()
        {
            // TODO unit test for the property 'AsyncJobID'
        }
    }
}
