/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DLP.Model;
using Cloudmersive.APIClient.NET.DLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DLP.Test.Model
{
    /// <summary>
    ///  Class for testing RedactedPageInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RedactedPageInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RedactedPageInfo
        //private RedactedPageInfo instance;

        public RedactedPageInfoTests()
        {
            // TODO uncomment below to create an instance of RedactedPageInfo
            //instance = new RedactedPageInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RedactedPageInfo
        /// </summary>
        [Fact]
        public void RedactedPageInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RedactedPageInfo
            //Assert.IsType<RedactedPageInfo>(instance);
        }

        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
    }
}
