/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DLP.Model;
using Cloudmersive.APIClient.NET.DLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DLP.Test.Model
{
    /// <summary>
    ///  Class for testing RedactedAudioSegment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RedactedAudioSegmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RedactedAudioSegment
        //private RedactedAudioSegment instance;

        public RedactedAudioSegmentTests()
        {
            // TODO uncomment below to create an instance of RedactedAudioSegment
            //instance = new RedactedAudioSegment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RedactedAudioSegment
        /// </summary>
        [Fact]
        public void RedactedAudioSegmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" RedactedAudioSegment
            //Assert.IsType<RedactedAudioSegment>(instance);
        }

        /// <summary>
        /// Test the property 'StartTimeMs'
        /// </summary>
        [Fact]
        public void StartTimeMsTest()
        {
            // TODO unit test for the property 'StartTimeMs'
        }

        /// <summary>
        /// Test the property 'EndTimeMs'
        /// </summary>
        [Fact]
        public void EndTimeMsTest()
        {
            // TODO unit test for the property 'EndTimeMs'
        }

        /// <summary>
        /// Test the property 'RedactedText'
        /// </summary>
        [Fact]
        public void RedactedTextTest()
        {
            // TODO unit test for the property 'RedactedText'
        }
    }
}
